vmware-samples/packer-examples-for-vsphere

scripts/linux/photon-server-cleanup.sh

Corrected Sudo typo and added all to the clean command.

Correct Clean Command 

---

scripts/linux/photon-server-cleanup.sh

Signed-off-by: William Lam <wlam@vmware.com>
**Context of the Pull Request**
Update the correct package repo for Photon OS 3.x (See #6 for more details)
Issue Number: #6 

Update package repo to point to packages.vmware.com

---

README.md
build.sh

- Update `README.md` https://github.com/rainpole/packer-vsphere/commit/1fd327447bf73c2b7f55024dc255960f97c85a89
- Update `build.sh` https://github.com/rainpole/packer-vsphere/commit/25eadd3c7e92432bf4505f9c907b3ad6b83c205e
Issue Number: None
None

Update README.md and build.sh.

---

builds/linux/almalinux-8/http/ks.pkrtpl.hcl
builds/linux/centos-linux-8/http/ks.pkrtpl.hcl
builds/linux/centos-stream-8/http/ks.pkrtpl.hcl
builds/linux/redhat-linux-8/http/ks.pkrtpl.hcl
builds/linux/rocky-linux-8/http/ks.pkrtpl.hcl

Updated the`ks.pkrtpl.hcl ` for rhel/variants:
- Removed `install` and `authconfig` (deprecated)
- Simplified `bootloader`and  'reboot`
- Removed `selinux --enforcing` and `firstboot --disable` (defaults)
- Updated` %packages`to @core.
- Added removal of `iwl*firmware`
Updated the `ks.pkrtpl.hcl ` for rhel/variants:
- Removed `install` and `authconfig` (deprecated)
- Simplified `bootloader`and  'reboot`
- Removed `selinux --enforcing` and `firstboot --disable` (defaults)
- Updated` …

Update ks.pkrtpl.hcl for rhel/variants

---

build.sh

Update `build.sh` to remove `rm -f output-vmware-iso/*.ova`
Update `build.sh` to remove `rm -f output-vmware-iso/*.ova`
Issue Number: #68 
Closes: #68 

Update `build.sh` to remove `rm -f output-vmware-iso/*.ova`

---

.gitignore

Fix missing wildcard in `.gitignore`
N/A

Fix typo in `.gitignore`

---

builds/linux/almalinux-8/data/ks.pkrtpl.hcl
builds/linux/centos-linux-8/data/ks.pkrtpl.hcl
builds/linux/centos-stream-8/data/ks.pkrtpl.hcl
builds/linux/rocky-linux-8/data/ks.pkrtpl.hcl

Adds the ansible package and dependencies to rhel-variants.
Adds Snsible to RHEL variants
Adds Ansible package and dependencies to RHEL variants.

Add ansible to rhel-variants

---

scripts/linux/redhat-linux.sh
scripts/linux/redhat-variant.sh

Refactor scripts to use `dnf` for RHEL8 and RHEL8-variants.
Refactor to use the DNF (Dandified YUM) software package manager. DNF is the successor of YUM (Yellowdog Updater Modified) and is the default package manager for RHEL8 and variants.

Refactor scripts to use `dnf` for rhel8 + rhel8-variants

---

README.md
builds/linux/almalinux-8/linux-almalinux.pkr.hcl
builds/linux/centos-linux-8/linux-centos-linux.pkr.hcl
builds/linux/centos-stream-8/linux-centos-stream.pkr.hcl
builds/linux/photon-4/linux-photon.pkr.hcl
builds/linux/redhat-linux-8/linux-redhat-linux.pkr.hcl
builds/linux/rocky-linux-8/linux-rocky-linux.pkr.hcl
builds/linux/ubuntu-server-18-04-lts/linux-ubuntu-server.pkr.hcl
builds/linux/ubuntu-server-20-04-lts/linux-ubuntu-server.pkr.hcl
builds/windows/windows-server-2016/windows-server.pkr.hcl
builds/windows/windows-server-2019/windows-server.pkr.hcl
builds/windows/windows-server-2022/windows-server.pkr.hcl

Update Packer to `>= 1.7.6`.
Updating Packer to `>= 1.7.6`.
```
packer {
required_version = ">= 1.7.6"
required_plugins {
vsphere = {
version = ">= v1.0.1"
source  = "github.com/hashicorp/vsphere"
}
}
required_plugins {
...
}
}
}
```

Update Packer to `>= 1.7.6`

---

.gitignore

Add public keys to `.gitignore`
Adds `**/*.pub` for public keys to `.gitignore`

Add public keys to `.gitignore`

---

scripts/linux/redhat-linux.sh

date method for adding epel repository for rhel8
Updates the method to enable the EPEL repository for RHEL8.
`sudo dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm`
Issue Number: #95 
Closes: #95

Update method for adding epel repository for rhel8

---

.github/ISSUE_TEMPLATE/bug.yml

Adds project versions and 'main` to issue template
Adds project versions and 'main` to issue template

Add project version and 'main` to issue template

---

.github/ISSUE_TEMPLATE/docs.yml
.github/ISSUE_TEMPLATE/enhancement.yml

Update issue templates.
- Adds dropdown for project version to `docs.yml`
- Adds the mention of the GitHub Discussions in the `enhancement.yml`

Update issue templates

---

builds/linux/redhat-linux-8/data/ks.pkrtpl.hcl
builds/linux/redhat-linux-8/linux-redhat-linux.pkr.hcl
scripts/linux/redhat-linux.sh

Add the ansible package and dependencies to rhel
- Moves RSHM registration to the kickstart process.
- Moves installation of the EPEL repository to the kickstart process.
- Updates provisioner script to check RHSM (via refresh) before installing additional packages.
Note: The provisioner script will, by design, continue to unregister RHSM after additional packages are installed.
Issue Number: #54 
**Breaking …

Add the ansible package and dependencies to rhel

---

README.md
build.sh
builds/linux/almalinux-8/linux-almalinux.auto.pkrvars.hcl
builds/linux/centos-linux-7/data/ks.pkrtpl.hcl
builds/linux/centos-linux-7/linux-centos-linux.auto.pkrvars.hcl
builds/linux/centos-linux-7/linux-centos-linux.pkr.hcl
builds/linux/centos-linux-7/variables.pkr.hcl
builds/linux/centos-linux-8/linux-centos-linux.auto.pkrvars.hcl
builds/linux/centos-stream-8/linux-centos-stream.auto.pkrvars.hcl
builds/linux/redhat-linux-7/data/ks.pkrtpl.hcl
builds/linux/redhat-linux-7/linux-redhat-linux.auto.pkrvars.hcl
builds/linux/redhat-linux-7/linux-redhat-linux.pkr.hcl
builds/linux/redhat-linux-7/variables.pkr.hcl
builds/linux/redhat-linux-8/linux-redhat-linux.auto.pkrvars.hcl
scripts/linux/rhel7-derivative.sh
scripts/linux/rhel7.sh
scripts/linux/rhel8-derivative.sh
scripts/linux/rhel8.sh

Look who's back again: RHEL 7 and CentOS 7. 😉 
(Sorry I booted you both in v21.08. 😆 )
- Adds the builds and includes Ansible in each kickstart.
- Renames the scripts for RHEL/RHEL derivatives based on major versions.
- Updates `build.sh`.
- Updates `README.md`.
**Related to Existing Discussion**
Discussion: #101 

Add RHEL 7 and CentOS 7

---

builds/linux/almalinux-8/data/ks.pkrtpl.hcl
builds/linux/centos-linux-7/data/ks.pkrtpl.hcl
builds/linux/centos-linux-8/data/ks.pkrtpl.hcl
builds/linux/centos-stream-8/data/ks.pkrtpl.hcl
builds/linux/redhat-linux-7/data/ks.pkrtpl.hcl
builds/linux/redhat-linux-8/data/ks.pkrtpl.hcl
builds/linux/rocky-linux-8/data/ks.pkrtpl.hcl
scripts/linux/rhel7-derivative.sh
scripts/linux/rhel7.sh
scripts/linux/rhel8-derivative.sh
scripts/linux/rhel8.sh

Updates rhel/rhel-derivative kickstart configurations and scripts
- Adds header to kickstart configurations.
- Adds comments for easier reference.
- Adds logical volume with partitions that aim to follow CIS partition rules.
- Moves the generated cleanup script to `/home/$BUILD_USERNAME/` due to `noexec` on `/tmp`.

Update rhel/rhel-derivative kickstart configurations and scripts

---

builds/linux/almalinux-8/data/ks.pkrtpl.hcl
builds/linux/centos-linux-7/data/ks.pkrtpl.hcl
builds/linux/centos-linux-8/data/ks.pkrtpl.hcl
builds/linux/centos-stream-8/data/ks.pkrtpl.hcl
builds/linux/redhat-linux-7/data/ks.pkrtpl.hcl
builds/linux/redhat-linux-8/data/ks.pkrtpl.hcl
builds/linux/rocky-linux-8/data/ks.pkrtpl.hcl

Fixes typo in rhel/rhel-derivative kickstart.
Fixes typo in rhel/rhel-derivative kickstart.

Fix typo in rhel/rhel-derivative kickstart

---

scripts/linux/photon.sh

Updates `photon.sh` to remove duplicate packages:
Updates `photon.sh` to remove duplicate packages:
- `ca-certificates` and `curl` already installed.
- removed second install (whoops!) of `openssl-c_rehash`.

Update `photon.sh` to remove duplicate package installs

---

builds/linux/photon-4/data/ks.pkrtpl.hcl

Adds initial `partitions` to `ks.pkrtpl.hcl` for Photon OS.
Tis s the initial configuration. Plan to modify to LVM with CIS-like settings for LVs.
Adds initial `partitions` to `ks.pkrtpl.hcl` for Photon OS.

Add `partitions` to `ks.pkrtpl.hcl` for photon

---

scripts/linux/ubuntu-server-2x.sh

Fixes symbol error.
Fixes symbol error.
Closes #141 

Fix symbol error in `ubuntu-server-2x.sh`

---

.github/comment_template.md
.github/workflows/issue-greeting.yml
.github/workflows/lock.yml
.github/workflows/pull-request-sizing.yml
.github/workflows/pull-request-wip.yml
.github/workflows/stale.yml

Adds GitHub Actions,
Please describe: GitHub Actions for Issues and Pull Requests
Adds GitHub Actions for:
- Size Pull Requests
- Skip WIP Pull Requests
- Add Issue Greeting
- Lock Issues and Pull Requests
- Stale Issues and Pull Requests

Adds GiitHub Actions

---

builds/windows/desktop/11/windows.auto.pkrvars.hcl
builds/windows/desktop/11/windows.pkr.hcl
builds/windows/server/2022/windows-server.auto.pkrvars.hcl

- Update Windows Server 2022 to the updated January 2022 .iso.
- Update Windows 11 to the updated January 2022 .iso.
Please describe: 🧹 Chore

Updates post-v22.01

---

MAINTAINERS.md

Updates to remove the term `active`.

Update content in `MAINTANERS.md`

---

.github/ISSUE_TEMPLATE/bug.yml
README.md
builds/linux/almalinux/8/linux-almalinux.pkr.hcl
builds/linux/centos/7/linux-centos.pkr.hcl
builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
builds/linux/centos/8/linux-centos.pkr.hcl
builds/linux/photon/4/linux-photon.pkr.hcl
builds/linux/rhel/7/linux-rhel.pkr.hcl
builds/linux/rhel/8/linux-rhel.pkr.hcl
builds/linux/rocky/8/linux-rocky.pkr.hcl
builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
builds/windows/desktop/10/windows.pkr.hcl
builds/windows/desktop/11/windows.pkr.hcl
builds/windows/server/2016/windows-server.pkr.hcl
builds/windows/server/2019/windows-server.pkr.hcl
builds/windows/server/2022/windows-server.pkr.hcl
terraform/vsphere-role/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf
terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf
terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf
terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf

Updates versions for dependencies:
- Packer v1.8.0
- Terraform v1.1.7
- Terraform Provider for VMware vSphere v2.1.1
Please describe: chore

chore: :arrow_up: Update dependencies

---

builds/linux/almalinux/8/data/ks.pkrtpl.hcl
builds/linux/centos/7/data/ks.pkrtpl.hcl
builds/linux/centos/8-stream/data/ks.pkrtpl.hcl
builds/linux/centos/8/data/ks.pkrtpl.hcl
builds/linux/photon/4/data/ks.pkrtpl.hcl
builds/linux/rhel/7/data/ks.pkrtpl.hcl
builds/linux/rhel/8/data/ks.pkrtpl.hcl
builds/linux/rocky/8/data/ks.pkrtpl.hcl
builds/linux/ubuntu/18-04-lts/data/ks.pkrtpl.hcl
builds/linux/ubuntu/20-04-lts/data/user-data.pkrtpl.hcl

Removes the local Ansible package from each Linux build as it is not required for the `ansible` provisioner.

refactor: :recycle: Remove Ansible package

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/docs.yml

Updates versions in issue templates and remove any past n-2.
Please describe: chore

chore: :arrow_up:  Update versions in `issue_templates`

---

builds/linux/almalinux/8/linux-almalinux.pkr.hcl

Updates Python interpreter for Ansible on AlmaLinux.
Closes #181

fix: :wrench: Update Python interpreter for Ansible on AlmaLinux

---

builds/linux/ubuntu/20-04-lts/linux-ubuntu.auto.pkrvars.hcl
builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl

Update `iso_file` and `iso_checksum` in `builds/linux/ubuntu/20-04-lts/linux-ubuntu.auto.pkrvars.hcl`.
Issue Number: #183

chore: ♻️ Update Ubuntu 20.04 LTS .iso to v20.04.4

---

.github/workflows/code-quality.yml
README.md
build.sh
build.tmpl
build.yaml

Added a configuration file and a script template to generate a build script.
[gomplate](https://gomplate.ca/) is required to generate the build script.
The build script is generated using the following command:
```
gomplate -c build.yaml -f build.tmpl -o build.sh
```
Closes #187

feat: Add a configurable build script

---

README.md
ansible/roles/configure/tasks/ubuntu.yml
build.sh
build.yaml
builds/linux/ubuntu/22-04-lts/data/user-data.pkrtpl.hcl
builds/linux/ubuntu/22-04-lts/linux-ubuntu.auto.pkrvars.hcl
builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/22-04-lts/variables.pkr.hcl

Ubuntu 22.04 will be published soon.
To anticipate, I prepare its build.
Closes #186

feat: Prepare Ubuntu 22.04

---

README.md

Fixing up step 1.2.3 in uploading ISOs as the example config directories were back to front
#
Currently in step 1.2.3, it shows the example config files as
>Example: `builds/<type>/<build>/*.auto.pkvars.hcl`
>
>```
>common_iso_datastore = "sfo-w01-cl01-ds-nfs01"
>```
>
>Example: `config/common.pkvars.hcl`
>
>```
>iso_path           = "iso/linux/photon"
>iso_file           = "photon-4.0-xxxxxxxxx.iso"
>iso_checksum_type  = "md5"
>iso_checksum_value = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
>```
However the example path and the example contents are the opposite of what they …

docs: Fix a mistake in README.md for Configuration, Step 2.3

---

build.sh
build.yaml
builds/linux/ubuntu/22-04-lts/linux-ubuntu.auto.pkrvars.hcl

Update the Ubuntu 22.04 LTS machine image for the generally available release
Issue Number: #196

Update the Ubuntu 22.04 LTS for GA release

---

builds/linux/centos/7/linux-centos.auto.pkrvars.hcl

#
689531cce9cf484378481ae762fae362791a9be078fda10e4f6977bf8fa71350 is sha256 of CentOS-7-x86_64-Everything-2009.iso

fix: Update checksum for CentOS 7 (`CentOS-7-x86_64-DVD-2009.iso`)

---

CONTRIBUTING.md

Update community documentation:
- CONTRIBUTING.md
- MAINTAINERS.md

docs: Update community documentation

---

terraform/vsphere-role/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf
terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf
terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf
terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf

Update to Terraform 1.2.1
Please describe: Chore

chore: Update to Terraform 1.2.1

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/docs.yml
.github/ISSUE_TEMPLATE/enhancement.yml

Updates issue templates for v22.06 release.
Please describe: chore / repo

repo: update issue templates for v22.06

---

.github/ISSUE_TEMPLATE/bug.yml
CHANGELOG.md
README.md
builds/linux/almalinux/8/linux-almalinux.pkr.hcl
builds/linux/centos/7/linux-centos.pkr.hcl
builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
builds/linux/centos/8/linux-centos.pkr.hcl
builds/linux/photon/4/linux-photon.pkr.hcl
builds/linux/rhel/7/linux-rhel.pkr.hcl
builds/linux/rhel/8/linux-rhel.pkr.hcl
builds/linux/rocky/8/linux-rocky.pkr.hcl
builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
builds/windows/desktop/10/windows.pkr.hcl
builds/windows/desktop/11/windows.pkr.hcl
builds/windows/server/2016/windows-server.pkr.hcl
builds/windows/server/2019/windows-server.pkr.hcl
builds/windows/server/2022/windows-server.pkr.hcl

Bump [`github.com/hashicorp/vsphere`](https://github.com/hashicorp/packer-plugin-vsphere/releases/tag/v1.0.6) from 1.0.5 to 1.0.6.
Please describe: `chore(deps)`

chore(deps): Bump `github.com/hashicorp/vsphere` from 1.0.5 to 1.0.6

---

README.md
ansible/roles/clean/tasks/redhat.yml
build.sh
build.yaml
builds/linux/almalinux/8/linux-almalinux.auto.pkrvars.hcl
builds/linux/almalinux/8/variables.pkr.hcl
builds/linux/almalinux/9/data/ks.pkrtpl.hcl
builds/linux/almalinux/9/linux-almalinux.auto.pkrvars.hcl
builds/linux/almalinux/9/linux-almalinux.pkr.hcl
builds/linux/almalinux/9/variables.pkr.hcl
builds/linux/centos/7/variables.pkr.hcl
builds/linux/centos/8-stream/variables.pkr.hcl
builds/linux/centos/9-stream/data/ks.pkrtpl.hcl
builds/linux/centos/9-stream/linux-centos-stream.auto.pkrvars.hcl
builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
builds/linux/centos/9-stream/variables.pkr.hcl
builds/linux/rhel/7/variables.pkr.hcl
builds/linux/rhel/9/data/ks.pkrtpl.hcl
builds/linux/rhel/9/linux-rhel.auto.pkrvars.hcl
builds/linux/rhel/9/linux-rhel.pkr.hcl
builds/linux/rhel/9/variables.pkr.hcl
builds/linux/rocky/8/linux-rocky.auto.pkrvars.hcl
builds/linux/rocky/8/variables.pkr.hcl

* Adds Red Hat Enterprise Linux 9
* Adds CentOS 9 Stream
* Adds AlmaLinux OS 9
* Updates Rocky Linux 8 to use `other4xLinuxGuest64`
* Updates Almalinux 8 to use `other4xLinuxGuest64`
- Update variable examples
Issue Number: #203

Add support for RHEL 9.0 + GA Derivatives

---

CHANGELOG.md
README.md
terraform/vsphere-role/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf
terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf
terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf
terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf

Bumps the `terraform` from `>= v1.2.3`  to `>= v1.2.5`.
Please describe: `chore/(deps)`

chore(deps): Bump `terraform` from `>= v1.2.3`  to `>= v1.2.5`

---

CHANGELOG.md
build.sh
build.yaml
builds/linux/rocky/9/data/ks.pkrtpl.hcl
builds/linux/rocky/9/linux-rocky.auto.pkrvars.hcl
builds/linux/rocky/9/linux-rocky.pkr.hcl
builds/linux/rocky/9/variables.pkr.hcl

Adds Rocky Linux 9
Closes #203

feat: Add support for RHEL 9.0 + GA derivatives (2 of 2)

---

CHANGELOG.md
builds/linux/almalinux/8/linux-almalinux.pkr.hcl
builds/linux/almalinux/9/linux-almalinux.pkr.hcl
builds/linux/centos/7/linux-centos.pkr.hcl
builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
builds/linux/photon/4/linux-photon.pkr.hcl
builds/linux/rhel/7/linux-rhel.pkr.hcl
builds/linux/rhel/8/linux-rhel.pkr.hcl
builds/linux/rhel/9/linux-rhel.pkr.hcl
builds/linux/rocky/8/linux-rocky.pkr.hcl
builds/linux/rocky/9/linux-rocky.pkr.hcl
builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
builds/windows/desktop/10/windows.pkr.hcl
builds/windows/desktop/11/windows.pkr.hcl
builds/windows/server/2019/windows-server.pkr.hcl
builds/windows/server/2022/windows-server.pkr.hcl

- Refactors builds to use local variables for virtual machine image names and descriptions.
- Refactors builds to use local variables for ISO paths and checksums.
- Refactors builds to use local variables for manifest data and output path.

refactor: Additional use of local variables

---

.github/comment_template.md

Update comment template.
Please describe: chore

chore: Update comment template

---

.github/dependabot.yml

Updates dependebot configuration for Terraform.
Please describe: chore

chore: Update dependebot configuration

---

.github/dependabot.yml
.github/generate-dependabot.sh

Adds script to auto-generate the `.github/dependabot.yml` configuration file.
To be added later to the CI checks.

chore: Auto-generate `.github/dependabot.yml`

---

ansible/roles/base/tasks/debian.yml
ansible/roles/base/tasks/main.yml
ansible/roles/clean/tasks/debian.yml
ansible/roles/clean/tasks/main.yml
ansible/roles/configure/tasks/debian.yml
ansible/roles/configure/tasks/main.yml
ansible/roles/users/tasks/main.yml

Adds Ansible playbooks for the Debian 11 machine image.
Assists #194

feat: add Debian 11 machine image Ansible playbooks

---

builds/linux/almalinux/8/linux-almalinux.pkr.hcl
builds/linux/almalinux/9/linux-almalinux.pkr.hcl
builds/linux/centos/7/linux-centos.pkr.hcl
builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
builds/linux/debian/11/linux-debian.pkr.hcl
builds/linux/photon/4/linux-photon.pkr.hcl
builds/linux/rhel/7/linux-rhel.pkr.hcl
builds/linux/rhel/8/linux-rhel.pkr.hcl
builds/linux/rhel/9/linux-rhel.pkr.hcl
builds/linux/rocky/8/linux-rocky.pkr.hcl
builds/linux/rocky/9/linux-rocky.pkr.hcl
builds/linux/sles/15/linux-sles.pkr.hcl
builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
builds/windows/desktop/10/windows.pkr.hcl
builds/windows/desktop/11/windows.pkr.hcl
builds/windows/server/2019/windows-server.pkr.hcl
builds/windows/server/2022/windows-server.pkr.hcl

Bumps:
- Packer from v1.8.2 to v1.8.3
- Packer plugin for vSphere from v1.0.6 to v1.0.7

chore(deps): bump Packer plugin for vSphere from v1.0.6 to v1.0.7

---

README.md
terraform/vsphere-role/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf
terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf
terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf
terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf

Bumps Terraform from v1.2.5 to v1.2.7

chore(deps): bump Terraform from v1.2.5 to v1.2.7

---

CHANGELOG.md
README.md
builds/linux/almalinux/8/linux-almalinux.pkr.hcl
builds/linux/almalinux/9/linux-almalinux.pkr.hcl
builds/linux/centos/7/linux-centos.pkr.hcl
builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
builds/linux/debian/11/linux-debian.pkr.hcl
builds/linux/photon/4/linux-photon.pkr.hcl
builds/linux/rhel/7/linux-rhel.pkr.hcl
builds/linux/rhel/8/linux-rhel.pkr.hcl
builds/linux/rhel/9/linux-rhel.pkr.hcl
builds/linux/rocky/8/linux-rocky.pkr.hcl
builds/linux/rocky/9/linux-rocky.pkr.hcl
builds/linux/sles/15/linux-sles.pkr.hcl
builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
builds/windows/desktop/10/windows.pkr.hcl
builds/windows/desktop/11/windows.pkr.hcl
builds/windows/server/2019/windows-server.pkr.hcl
builds/windows/server/2022/windows-server.pkr.hcl

Bumps Packer plugin for vSphere from v1.0.7 to v1.0.8.

chore(deps): bump Packer plugin for vSphere from v1.0.7 to v1.0.8

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/docs.yml
.github/pull_request_template.md

Update versions in the `.github/ISSUE_TEMPLATES` for `v22.07`.

chore: Update versions in the `.github/ISSUE_TEMPLATES` for `v22.07`.

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/docs.yml
.github/pull_request_template.md

Update versions in the `.github/ISSUE_TEMPLATES` for `v22.08`.

chore: Update versions in the `.github/ISSUE_TEMPLATES` for `v22.08`.

---

CHANGELOG.md
README.md
terraform/vsphere-role/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf
terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-template-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf
terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf
terraform/vsphere-virtual-machine/template-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf

Bumps Terraform from v1.2.7 to v1.2.8.
Signed-off-by: Ryan Johnson johnsonryan@vmware.com

chore(deps): bump Terraform from v1.2.7 to v1.2.8

---

builds/linux/debian/11/linux-debian.auto.pkrvars.hcl

Bumps Debian 11 from 11.4.0 to 11.5.0.

chore(deps): bump debian from v11.4.0 to v11.5.0

---

builds/linux/ubuntu/20-04-lts/linux-ubuntu.auto.pkrvars.hcl

Bumps Ubuntu 20.04 from v20.04.4 to v20.04.5.

chore(deps): bump ubuntu from v20.04.4 to v20.04.5

---

builds/linux/almalinux/8/linux-almalinux.pkr.hcl
builds/linux/almalinux/9/linux-almalinux.pkr.hcl
builds/linux/centos/7/linux-centos.pkr.hcl
builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
builds/linux/debian/11/linux-debian.pkr.hcl
builds/linux/photon/4/linux-photon.pkr.hcl
builds/linux/rhel/7/linux-rhel.pkr.hcl
builds/linux/rhel/8/linux-rhel.pkr.hcl
builds/linux/rhel/9/linux-rhel.pkr.hcl
builds/linux/rocky/8/linux-rocky.pkr.hcl
builds/linux/rocky/9/linux-rocky.pkr.hcl
builds/linux/sles/15/linux-sles.pkr.hcl
builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
builds/windows/desktop/10/windows.pkr.hcl
builds/windows/desktop/11/windows.pkr.hcl
builds/windows/server/2019/windows-server.pkr.hcl
builds/windows/server/2022/windows-server.pkr.hcl

Updates formatting on `.hcl` files.
```bash
➜ packer fmt -recursive .
builds/linux/almalinux/8/linux-almalinux.pkr.hcl
builds/linux/almalinux/9/linux-almalinux.pkr.hcl
builds/linux/centos/7/linux-centos.pkr.hcl
builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
builds/linux/debian/11/linux-debian.pkr.hcl
builds/linux/photon/4/linux-photon.pkr.hcl
builds/linux/rhel/7/linux-rhel.pkr.hcl
builds/linux/rhel/8/linux-rhel.pkr.hcl
builds/linux/rhel/9/linux-rhel.pkr.hcl
builds/linux/rocky/8/linux-rocky.pkr.hcl
builds/linux/rocky/9/linux-rocky.pkr.hcl
builds/linux/sles/15/linux-sles.pkr.hcl
builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl …
```

chore: run `packer fmt`

---

builds/windows/server/2019/variables.pkr.hcl
builds/windows/server/2022/variables.pkr.hcl

fix: correct typos

---

builds/linux/almalinux/8/variables.pkr.hcl
builds/linux/almalinux/9/variables.pkr.hcl
builds/linux/centos/7/variables.pkr.hcl
builds/linux/centos/8-stream/variables.pkr.hcl
builds/linux/centos/9-stream/variables.pkr.hcl
builds/linux/debian/11/variables.pkr.hcl
builds/linux/photon/4/variables.pkr.hcl
builds/linux/rhel/7/variables.pkr.hcl
builds/linux/rhel/8/variables.pkr.hcl
builds/linux/rhel/9/variables.pkr.hcl
builds/linux/rocky/8/variables.pkr.hcl
builds/linux/rocky/9/variables.pkr.hcl
builds/linux/sles/15/variables.pkr.hcl
builds/linux/ubuntu/18-04-lts/variables.pkr.hcl
builds/linux/ubuntu/20-04-lts/variables.pkr.hcl
builds/linux/ubuntu/22-04-lts/variables.pkr.hcl
builds/windows/desktop/10/variables.pkr.hcl
builds/windows/desktop/11/variables.pkr.hcl
builds/windows/server/2019/variables.pkr.hcl
builds/windows/server/2022/variables.pkr.hcl

Removes unnecessary defaults:
- `vm_mem_hot_add` (Windows)
- `vm_cpu_hot_add` (Windows)
- `vsphere_insecure_connection` (All)

refactor: remove unnecessary defaults

---

CHANGELOG.md
README.md

Addresses `markdownlint` linter findings.

docs: address `markdownlint` findings

---

builds/windows/server/2019/windows-server.pkr.hcl
builds/windows/server/2022/windows-server.pkr.hcl

Fix mismatch in source names for Windows Server when builds are launched via script.

fix: update windows server source names

---

builds/windows/server/2022/windows-server.auto.pkrvars.hcl

Bumps Windows Server 2022 to the September 2022 release.
Signed-off-by: Ryan Johnson johnsonryan@vmware.com

chore(deps): bump windows server 2022 to september 2022

---

README.md
terraform/vsphere-role/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf
terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-template-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf
terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf
terraform/vsphere-virtual-machine/template-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf

Bumps Terraform from v1.2.8 to v1.3.0.

chore(deps): bump `terraform` from v1.2.8 to v1.3.0

---

README.md
builds/linux/sles/15/data/autoinst.pkrtpl.hcl
builds/linux/sles/15/linux-sles.auto.pkrvars.hcl

Bumps SLES 15 from v15.3 to v15.4.
cc @gcblack 
Closes #259

chore(deps): bump sles from v15.3 to v15.4

---

README.md
terraform/vsphere-role/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf
terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-template-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf
terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf
terraform/vsphere-virtual-machine/template-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf

Bumps Terraform from v1.3.0 to v1.3.1.

chore(deps): bump terraform from v1.3.0 to v1.3.1

---

README.md
terraform/vsphere-role/terraform.tfvars.example

Adds a known. but missing privilege to `README.md` configuration section and the Terraform example for a custom vSphere role.
#293

fix: add privilege

---

.github/dependabot.yml
.github/generate-dependabot.sh

Updates dependabot:
- configuration generation script linting
- to latest configuration output

chore(gh): update dependabot

---

MAINTAINERS.md

Updates `MAINTAINERS.md` based on linter finding(s).

chore: update `MAINTAINERS.md`

---

.github/comment-template.md

Updates based on linter finding(s).

chore(gh): update comment template

---

.github/pull_request_template.md

Updates based on linter finding(s).

chore(gh): update pull request template

---

set-envvars.sh

Updates based on linter finding(s).

chore: update `set-envvars.sh`

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/docs.yml
.github/ISSUE_TEMPLATE/enhancement.yml

Updates based on linter finding(s) and general simplification.

chore(gh): update issue templates

---

.github/workflows/issue-greeting.yml
.github/workflows/lock-threads.yml
.github/workflows/pull-request-sizing.yml
.github/workflows/stale.yml

Updates based on linter finding(s) and general simplification.

chore(gh): update actions

---

CODE_OF_CONDUCT.md

Updates `CODE_OF_CONDUCT.md` based on linter finding(s).

chore: update `CODE_OF_CONDUCT.md`

---

build.sh
build.yaml
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/metadata.yml
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/userdata.yml

Updates build files based on linter finding(s).

chore: update build configuration

---

config.sh

Updates configuration generation based on linter finding(s).

chore: update configuration generation

---

terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/main.tf
terraform/vsphere-virtual-machine/template-linux-cloud-init/main.tf
terraform/vsphere-virtual-machine/template-linux-guest-customization/main.tf
terraform/vsphere-virtual-machine/template-windows-guest-customization-hcp-packer/main.tf
terraform/vsphere-virtual-machine/template-windows-guest-customization/main.tf

Updates Terraform examples to ensure list items are accessed using square brackets.

fix: update terraform deprecated index

---

terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/metadata.yml
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/userdata.yml
terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/userdata.yml
terraform/vsphere-virtual-machine/template-linux-cloud-init/userdata.yml

Updates the  cloud-init YAML based on linter finding(s).

chore: update cloud-init YAML

---

.github/CODEOWNERS

Updates `CODEOWNERS` to direct reviews to the maintainers team vs an individual.

chore(gh): update `CODEOWNERS`

---

.gitignore
.gitleaksignorek
CHANGELOG.md

Updates `CHANGELOG.md` based on linter finding(s).

docs: update `CHANGELOG.md`

---

.github/ISSUE_TEMPLATE/bug.yml
README.md
builds/linux/almalinux/8/linux-almalinux.pkr.hcl
builds/linux/almalinux/9/linux-almalinux.pkr.hcl
builds/linux/centos/7/linux-centos.pkr.hcl
builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
builds/linux/debian/11/linux-debian.pkr.hcl
builds/linux/photon/4/linux-photon.pkr.hcl
builds/linux/rhel/7/linux-rhel.pkr.hcl
builds/linux/rhel/8/linux-rhel.pkr.hcl
builds/linux/rhel/9/linux-rhel.pkr.hcl
builds/linux/rocky/8/linux-rocky.pkr.hcl
builds/linux/rocky/9/linux-rocky.pkr.hcl
builds/linux/sles/15/linux-sles.pkr.hcl
builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
builds/windows/desktop/10/windows.pkr.hcl
builds/windows/desktop/11/windows.pkr.hcl
builds/windows/server/2019/windows-server.pkr.hcl
builds/windows/server/2022/windows-server.pkr.hcl

Bumps Packer from v1.8.3 to v1.8.4.

chore(deps): bump packer from v1.8.3 to v1.8.4

---

.github/ISSUE_TEMPLATE/bug.yml
README.md
builds/linux/almalinux/8/linux-almalinux.pkr.hcl
builds/linux/almalinux/9/linux-almalinux.pkr.hcl
builds/linux/centos/7/linux-centos.pkr.hcl
builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
builds/linux/debian/11/linux-debian.pkr.hcl
builds/linux/photon/4/linux-photon.pkr.hcl
builds/linux/rhel/7/linux-rhel.pkr.hcl
builds/linux/rhel/8/linux-rhel.pkr.hcl
builds/linux/rhel/9/linux-rhel.pkr.hcl
builds/linux/rocky/8/linux-rocky.pkr.hcl
builds/linux/rocky/9/linux-rocky.pkr.hcl
builds/linux/sles/15/linux-sles.pkr.hcl
builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
builds/windows/desktop/10/windows.pkr.hcl
builds/windows/desktop/11/windows.pkr.hcl
builds/windows/server/2019/windows-server.pkr.hcl
builds/windows/server/2022/windows-server.pkr.hcl

Bumps Packer Plugin for vSphere from v1.0.8 to v1.1.0.

chore(deps): bump packer-plugin-vsphere from v1.0.8 to v1.1.0

---

README.md
terraform/vsphere-role/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf
terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-template-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf
terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf
terraform/vsphere-virtual-machine/template-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf

Bumps Terraform from v1.3.1 to v1.3.4.

chore(deps): bump terraform from v1.3.1 to v1.3.4

---

.gitleaks.toml

Add Gitleaks configuration file for github/super-linter use.

chore(gh): add `.gitleaks.toml`

---

scripts/windows/windows-prepare.ps1

Add support for disabling password expiration for the local administrator account (non-English) localized Windows guest operating systems.
Closes: #332

feat: localized local administrator

---

scripts/windows/windows-prepare.ps1

Add support for enabling Remote Desktop on (non-English) localized Windows guest operating systems.
Closes: #333

feat: localized remote desktop

---

builds/linux/debian/11/linux-debian.auto.pkrvars.hcl

Updates Debian 11 to use thin provisioning, by default, to align with the other examples; however, this is configurable.
Closes #341

refactor: update debian disk provisioning

---

MAINTAINERS.md

docs: update `MAINTAINERS.md`

---

builds/linux/almalinux/8/linux-almalinux.auto.pkrvars.hcl

- Bumps Almalinux 8 from v8.6 to v8.7.

chore(deps): bump almalinux from v8.6 to v8.7

---

builds/linux/almalinux/9/linux-almalinux.auto.pkrvars.hcl

- Bumps Almalinux 9 from v9.0 to v9.1.

chore(deps): bump almalinux from v9.0 to v9.1

---

builds/linux/rhel/8/linux-rhel.auto.pkrvars.hcl

- Bumps Red Hat Enterprise Linux 8 from v8.6 to v8.7.

chore(deps): bump rhel from v8.6 to v8.7

---

builds/linux/rhel/9/linux-rhel.auto.pkrvars.hcl

- Bumps Red Hat Enterprise Linux from v9.0 to v9.1.

chore(deps): bump rhel from v9.0 to v9.1

---

builds/linux/rocky/9/linux-rocky.auto.pkrvars.hcl

Updates the `vm_guest_os_version` to use the x.y version.

chore: update rocky linux 9 `vm_guest_os_version`

---

builds/linux/rocky/8/linux-rocky.auto.pkrvars.hcl

- Bumps Rocky Linux 8 from v8.6 to v8.7.

chore(deps): bump rocky linux from v8.6 to v8.7

---

builds/linux/debian/11/linux-debian.auto.pkrvars.hcl

Updates the `vm_guest_os_version` to use the x.y version.

chore: update debian `vm_guest_os_version`

---

builds/linux/photon/4/linux-photon.auto.pkrvars.hcl

Updates the `vm_guest_os_version` to use the x.y version.

chore: update photon 4 `vm_guest_os_version`

---

builds/linux/sles/15/linux-sles.auto.pkrvars.hcl

Updates the `vm_guest_os_version` to use the x.y version.

chore: update sles `vm_guest_os_version`

---

builds/windows/server/2019/windows-server.auto.pkrvars.hcl

Bumps Windows Server 2019 to November 2022 release.

chore(deps): bump windows server 2019 to latest

---

builds/windows/desktop/10/windows.auto.pkrvars.hcl

Bumps Windows 10 to the 22H2 November 2022 release.

chore(deps): bump windows 10 to 22h2 november 2022

---

builds/windows/desktop/11/windows.auto.pkrvars.hcl

Bumps Windows 11 to the 22H2 November 2022 release.

chore(deps): bump windows 11 to 22h2 november 2022

---

README.md
terraform/vsphere-role/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf
terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-template-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf
terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf
terraform/vsphere-virtual-machine/template-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf

Bumps Terraform from v1.3.4 to v1.3.5.

chore(deps): bump terraform from v1.3.4 to v1.3.5

---

README.md

It seems that there was and advisory related to a dependency and they upped the version https://github.com/hairyhenderson/gomplate/releases/tag/v3.11.3

chore(deps): bump gomplate from v3.11.2 to v3.11.3

---

builds/linux/rocky/9/linux-rocky.auto.pkrvars.hcl

Bumps Rocky Linux 9 from v9.0 to v9.1.

chore(deps): bump rocky linux from v9.0 to v9.1

---

builds/linux/ubuntu/18-04-lts/linux-ubuntu.auto.pkrvars.hcl
builds/linux/ubuntu/20-04-lts/linux-ubuntu.auto.pkrvars.hcl
builds/linux/ubuntu/22-04-lts/linux-ubuntu.auto.pkrvars.hcl
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/terraform.tfvars.example
terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/terraform.tfvars.example
terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/terraform.tfvars.example
terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/terraform.tfvars.example
terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/terraform.tfvars.example

I think the version and the string "LTS" should be separated by a hyphen to improve readability. 

chore: add hyphen for version readability

---

README.md
terraform/vsphere-role/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf
terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-template-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf
terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf
terraform/vsphere-virtual-machine/template-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf

Bumps Terraform from v1.3.5 to v1.3.6.

chore(deps): bump terraform from v1.3.5 to v1.3.6

---

ansible/roles/configure/tasks/main.yml

Updates the task name for configuring RHEL derivative distributions.

fix(ansible): update configure task name

---

.github/ISSUE_TEMPLATE/bug.yml
README.md
builds/linux/almalinux/8/linux-almalinux.pkr.hcl
builds/linux/almalinux/9/linux-almalinux.pkr.hcl
builds/linux/centos/7/linux-centos.pkr.hcl
builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
builds/linux/debian/11/linux-debian.pkr.hcl
builds/linux/photon/4/linux-photon.pkr.hcl
builds/linux/rhel/7/linux-rhel.pkr.hcl
builds/linux/rhel/8/linux-rhel.pkr.hcl
builds/linux/rhel/9/linux-rhel.pkr.hcl
builds/linux/rocky/8/linux-rocky.pkr.hcl
builds/linux/rocky/9/linux-rocky.pkr.hcl
builds/linux/sles/15/linux-sles.pkr.hcl
builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
builds/windows/desktop/10/windows.pkr.hcl
builds/windows/desktop/11/windows.pkr.hcl
builds/windows/server/2019/windows-server.pkr.hcl
builds/windows/server/2022/windows-server.pkr.hcl

Bumps Packer Plugin for vSphere from v1.1.0 to v1.1.1.

chore(deps): bump packer-plugin-vsphere from v1.1.0 to v1.1.1

---

builds/linux/centos/8-stream/linux-centos-stream.auto.pkrvars.hcl

Bumps CentOS Stream 8 checksum to the latest release.

chore(deps): bump centos stream 8 to latest

---

builds/linux/centos/9-stream/linux-centos-stream.auto.pkrvars.hcl

Bumps CentOS Stream 9 checksum to the latest release.

chore(deps): bump centos stream 9 to latest

---

.github/ISSUE_TEMPLATE/bug.yml
CHANGELOG.md
README.md
builds/linux/almalinux/8/linux-almalinux.pkr.hcl
builds/linux/almalinux/9/linux-almalinux.pkr.hcl
builds/linux/centos/7/linux-centos.pkr.hcl
builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
builds/linux/debian/11/linux-debian.pkr.hcl
builds/linux/photon/4/linux-photon.pkr.hcl
builds/linux/rhel/7/linux-rhel.pkr.hcl
builds/linux/rhel/8/linux-rhel.pkr.hcl
builds/linux/rhel/9/linux-rhel.pkr.hcl
builds/linux/rocky/8/linux-rocky.pkr.hcl
builds/linux/rocky/9/linux-rocky.pkr.hcl
builds/linux/sles/15/linux-sles.pkr.hcl
builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
builds/windows/desktop/10/windows.pkr.hcl
builds/windows/desktop/11/windows.pkr.hcl
builds/windows/server/2019/windows-server.pkr.hcl
builds/windows/server/2022/windows-server.pkr.hcl

Bumps Packer from v1.8.4 to v1.8.5

chore(deps): bump packer from v1.8.4 to v1.8.5

---

builds/windows/server/2019/windows-server.pkr.hcl

Updates the `output_directory` for `windows-server-datacenter-core ` to use the correct local variable.
Closes #434

fix: update `output_directory` variable

---

builds/windows/desktop/10/windows.auto.pkrvars.hcl
builds/windows/desktop/10/windows.pkr.hcl
builds/windows/desktop/11/windows.auto.pkrvars.hcl
builds/windows/server/2019/windows-server.auto.pkrvars.hcl
builds/windows/server/2019/windows-server.pkr.hcl
builds/windows/server/2022/windows-server.auto.pkrvars.hcl
builds/windows/server/2022/windows-server.pkr.hcl

Reverts inclusion of additional `winrm` arguments slated for future enhancement.
Related #436

fix: revert winrm args

---

builds/linux/rhel/9/data/ks.pkrtpl.hcl

Updates the install commands to utilize EPEL repo for RHEL 9.
Closes #441

fix: update EPEL repo version for RHEL 9

---

ansible/roles/base/tasks/photon.yml
ansible/roles/clean/tasks/debian.yml
ansible/roles/clean/tasks/photon.yml
ansible/roles/clean/tasks/redhat.yml
ansible/roles/clean/tasks/sles.yml
ansible/roles/clean/tasks/ubuntu.yml
ansible/roles/configure/tasks/debian.yml
ansible/roles/configure/tasks/photon.yml
ansible/roles/configure/tasks/redhat.yml
ansible/roles/configure/tasks/sles.yml
ansible/roles/configure/tasks/ubuntu.yml
ansible/roles/users/tasks/linux.yml
ansible/roles/users/tasks/photon.yml

When using ansible-core 2.14 a build will fail with an error similar to:
```console
vsphere-iso.linux-photon: TASK [base : Updating the guest operating system.] *****************************
vsphere-iso.linux-photon: failed: [default] (item=tdnf -y update) => {"<sensitive>_loop_var": "item", "changed": false, "item": "tdnf -y update", "msg": "Unsupported parameters for (<sensitive>.legacy.command) module: warn. Supported parameters include: stdin_add_newline, executable, strip_empty_ends, _uses_shell, _raw_params, chdir, creates, argv, stdin, removes."}
```
This pull request semoves the `args: warn` for ansible-core 2.14 or later.
Example:
```yaml
args:
warn:false
```

refactor: remove `args: warn` for ansible-core 2.14+

---

CHANGELOG.md
README.md
ansible/roles/configure/tasks/debian.yml
builds/linux/debian/11/linux-debian.auto.pkrvars.hcl

Bumps Debian from v11.5 to v11.6.

chore(deps): bump debian from v11.5 to v11.6

---

LICENSE
NOTICE

chore: update copyright

---

terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/userdata.yml
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/userdata.yml
terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/userdata.yml
terraform/vsphere-virtual-machine/template-linux-cloud-init/userdata.yml

Updates the Terraform examples for the use of cloud-init to correctly add a user.
Resolves #299

fix: update cloud-init terraform examples

---

README.md

Update the link to Photon Kickstart documentation.
Issue Number: #474

fix: update photon-kickstart link

---

.github/ISSUE_TEMPLATE/bug.yml
CHANGELOG.md
README.md
builds/linux/almalinux/8/linux-almalinux.pkr.hcl
builds/linux/almalinux/9/linux-almalinux.pkr.hcl
builds/linux/centos/7/linux-centos.pkr.hcl
builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
builds/linux/debian/11/linux-debian.pkr.hcl
builds/linux/photon/4/linux-photon.pkr.hcl
builds/linux/rhel/7/linux-rhel.pkr.hcl
builds/linux/rhel/8/linux-rhel.pkr.hcl
builds/linux/rhel/9/linux-rhel.pkr.hcl
builds/linux/rocky/8/linux-rocky.pkr.hcl
builds/linux/rocky/9/linux-rocky.pkr.hcl
builds/linux/sles/15/linux-sles.pkr.hcl
builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
builds/windows/desktop/10/windows.pkr.hcl
builds/windows/desktop/11/windows.pkr.hcl
builds/windows/server/2019/windows-server.pkr.hcl
builds/windows/server/2022/windows-server.pkr.hcl

Bumps Packer from v1.8.5 to v1.8.6.

chore(deps): bump packer from v1.8.5 to v1.8.6

---

CHANGELOG.md
README.md
builds/linux/almalinux/8/linux-almalinux.pkr.hcl
builds/linux/almalinux/9/linux-almalinux.pkr.hcl
builds/linux/centos/7/linux-centos.pkr.hcl
builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
builds/linux/debian/11/linux-debian.pkr.hcl
builds/linux/photon/4/linux-photon.pkr.hcl
builds/linux/rhel/7/linux-rhel.pkr.hcl
builds/linux/rhel/8/linux-rhel.pkr.hcl
builds/linux/rhel/9/linux-rhel.pkr.hcl
builds/linux/rocky/8/linux-rocky.pkr.hcl
builds/linux/rocky/9/linux-rocky.pkr.hcl
builds/linux/sles/15/linux-sles.pkr.hcl
builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
builds/windows/desktop/10/windows.pkr.hcl
builds/windows/desktop/11/windows.pkr.hcl
builds/windows/server/2019/windows-server.pkr.hcl
builds/windows/server/2022/windows-server.pkr.hcl

Bumps Packer Plugin for Git from v0.3.2 to v0.3.3.

chore(deps): bump packer-plugin-git from v0.3.2 to v0.3.3

---

CHANGELOG.md
README.md
terraform/vsphere-role/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf
terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-template-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf
terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf
terraform/vsphere-virtual-machine/template-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf

Bumps Terraform from v1.3.7 to v1.3.9.

chore(deps): bump terraform from v1.3.7 to v1.3.9

---

CHANGELOG.md
builds/linux/ubuntu/22-04-lts/linux-ubuntu.auto.pkrvars.hcl

Bumps Ubuntu 22.04 from v22.04.1 to v22.04.2.
Signed-off-by: username-is-already-taken2 <digitalgaz@hotmail.com>

chore(deps): bump ubuntu from v22.04.1 to v22.04.2

---

README.md

Bumps gomplate from v3.11.3 to v3.11.4.
See https://github.com/hairyhenderson/gomplate/releases/tag/v3.11.4.

chore(deps): bump gomplate from v3.11.3 to v3.11.4

---

CHANGELOG.md
README.md

Bumps gomplate from v3.11.4 to v3.11.5.

chore(deps): bump gomplate from v3.11.4 to v3.11.5

---

CHANGELOG.md
README.md
terraform/vsphere-role/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf
terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-template-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf
terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf
terraform/vsphere-virtual-machine/template-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf

Bumps Terraform from v1.3.9 to v1.5.0.

chore(deps): bump terraform from v1.3.9 to v1.5.0

---

CHANGELOG.md
README.md
builds/linux/almalinux/8/linux-almalinux.pkr.hcl
builds/linux/almalinux/9/linux-almalinux.pkr.hcl
builds/linux/centos/7/linux-centos.pkr.hcl
builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
builds/linux/debian/11/linux-debian.pkr.hcl
builds/linux/photon/4/linux-photon.pkr.hcl
builds/linux/rhel/7/linux-rhel.pkr.hcl
builds/linux/rhel/8/linux-rhel.pkr.hcl
builds/linux/rhel/9/linux-rhel.pkr.hcl
builds/linux/rocky/8/linux-rocky.pkr.hcl
builds/linux/rocky/9/linux-rocky.pkr.hcl
builds/linux/sles/15/linux-sles.pkr.hcl
builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
builds/windows/desktop/10/windows.pkr.hcl
builds/windows/desktop/11/windows.pkr.hcl
builds/windows/server/2019/windows-server.pkr.hcl
builds/windows/server/2022/windows-server.pkr.hcl

Bumps Packer Plugin for Git (`ethanmdavidson/packer-plugin-git`) from v0.3.3 to v0.4.2.

chore(deps): bump packer-plugin-git from v0.3.3 to v0.4.2

---

.github/ISSUE_TEMPLATE/bug.yml
CHANGELOG.md
README.md
builds/linux/almalinux/8/linux-almalinux.pkr.hcl
builds/linux/almalinux/9/linux-almalinux.pkr.hcl
builds/linux/centos/7/linux-centos.pkr.hcl
builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
builds/linux/debian/11/linux-debian.pkr.hcl
builds/linux/photon/4/linux-photon.pkr.hcl
builds/linux/rhel/7/linux-rhel.pkr.hcl
builds/linux/rhel/8/linux-rhel.pkr.hcl
builds/linux/rhel/9/linux-rhel.pkr.hcl
builds/linux/rocky/8/linux-rocky.pkr.hcl
builds/linux/rocky/9/linux-rocky.pkr.hcl
builds/linux/sles/15/linux-sles.pkr.hcl
builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
builds/windows/desktop/10/windows.pkr.hcl
builds/windows/desktop/11/windows.pkr.hcl
builds/windows/server/2019/windows-server.pkr.hcl
builds/windows/server/2022/windows-server.pkr.hcl

Bumps Packer from v1.8.6 to v1.9.1.

chore(deps): bump packer from v1.8.6 to v1.9.1

---

.github/ISSUE_TEMPLATE/bug.yml
CHANGELOG.md
README.md
builds/linux/almalinux/8/linux-almalinux.pkr.hcl
builds/linux/almalinux/9/linux-almalinux.pkr.hcl
builds/linux/centos/7/linux-centos.pkr.hcl
builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
builds/linux/debian/11/linux-debian.pkr.hcl
builds/linux/photon/4/linux-photon.pkr.hcl
builds/linux/rhel/7/linux-rhel.pkr.hcl
builds/linux/rhel/8/linux-rhel.pkr.hcl
builds/linux/rhel/9/linux-rhel.pkr.hcl
builds/linux/rocky/8/linux-rocky.pkr.hcl
builds/linux/rocky/9/linux-rocky.pkr.hcl
builds/linux/sles/15/linux-sles.pkr.hcl
builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
builds/windows/desktop/10/windows.pkr.hcl
builds/windows/desktop/11/windows.pkr.hcl
builds/windows/server/2019/windows-server.pkr.hcl
builds/windows/server/2022/windows-server.pkr.hcl

Bumps Packer Plugin for vSphere (`hashicorp/packer-plugin-vsphere`) from  v1.1.1 to v1.2.0.

chore(deps): bump packer-plugin-vsphere from v1.1.1 to v1.2.0

---

CHANGELOG.md
README.md
builds/windows/desktop/10/windows.pkr.hcl
builds/windows/desktop/11/windows.pkr.hcl
builds/windows/server/2019/windows-server.pkr.hcl
builds/windows/server/2022/windows-server.pkr.hcl

Bumps Packer Plugin for Windows Updates (`rgl/packer-plugin-windows-update`) from v0.14.1 to v0.14.3.

chore(deps): bump packer-plugin-windows-update from v0.14.1 to v0.14.3

---

CHANGELOG.md
builds/linux/almalinux/9/linux-almalinux.auto.pkrvars.hcl

Bumps Almalinux 9 from v9.1 to v9.2.

chore(deps): bump almalinux from v9.1 to v9.2

---

CHANGELOG.md
builds/linux/almalinux/8/linux-almalinux.auto.pkrvars.hcl

Bumps Almalinux 8 from v8.7 to v8.8.

chore(deps): bump almalinux from v8.7 to v8.8

---

CHANGELOG.md
builds/linux/rocky/9/linux-rocky.auto.pkrvars.hcl

Bumps Rocky Linux 9 from v9.1 to v9.2.

chore(deps): bump rocky linux from v9.1 to v9.2

---

CHANGELOG.md
builds/linux/rocky/8/linux-rocky.auto.pkrvars.hcl

Bumps Rocky Linux 8 from v8.7 to v8.8.

chore(deps): bump rocky linux from v8.7 to v8.8

---

CHANGELOG.md
README.md

Updates ansible-core from v2.13 to v2.15.

chore(deps): update ansible-core from v2.13 to v2.15

---

.github/workflows/code-quality.yml
.github/workflows/issue-greeting.yml
.github/workflows/lock-threads.yml
.github/workflows/pull-request-sizing.yml
.github/workflows/stale.yml

Pin actions to a full length commit SHA.
Ref: [Security hardening for GitHub Actions](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions)

chore(gha): pin actions to commit sha

---

CHANGELOG.md
builds/linux/rhel/8/linux-rhel.auto.pkrvars.hcl

Bumps RHEL 8 from v8.7 to v8.8.

chore(deps): bump rhel from v8.7 to v8.8

---

CHANGELOG.md
README.md
build.sh
build.yaml
builds/linux/photon/5/data/ks.pkrtpl.hcl
builds/linux/photon/5/linux-photon.auto.pkrvars.hcl
builds/linux/photon/5/linux-photon.pkr.hcl
builds/linux/photon/5/variables.pkr.hcl

Adds VMware Photon OS 5.0 to the project.
Ref: #470
Closes #470

feat: add photon 5

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/docs.yml
.github/ISSUE_TEMPLATE/enhancement.yml
.github/workflows/code-quality.yml
CONTRIBUTING.md
README.md

Updates to reflect use of the `develop` branch.

chore: update to `develop` branch

---

.gitlab-ci.yml
CHANGELOG.md
README.md
build.sh
build.yaml
builds/windows/desktop/10/variables.pkr.hcl
builds/windows/desktop/10/windows.auto.pkrvars.hcl
builds/windows/desktop/10/windows.pkr.hcl
builds/windows/desktop/11/variables.pkr.hcl
builds/windows/desktop/11/windows.auto.pkrvars.hcl
builds/windows/desktop/11/windows.pkr.hcl

- Adds Windows 11 Enterprise to the project.
- Adds Windows 10 Enterprise to the project.
Resolves #687 
Issue Number: #687

feat: add support for windows 10/11 enterprise

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
CHANGELOG.md

- Adds development container.
- `./devcontainer/devcontainer.json`
- `./devcontainer/Dockerfile`
- Updates`CHANGELOG.md`.
Closes #696
Closes #703

chore: add devcontainer

---

CHANGELOG.md
set-envvars.sh

Adds Packer logging settings to `set-envvars.sh`.
Related #697

feat: add logging to `set-envvars.sh`

---

CHANGELOG.md
README.md
builds/linux/almalinux/8/linux-almalinux.pkr.hcl
builds/linux/almalinux/9/linux-almalinux.pkr.hcl
builds/linux/centos/7/linux-centos.pkr.hcl
builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
builds/linux/debian/11/linux-debian.pkr.hcl
builds/linux/debian/12/linux-debian.pkr.hcl
builds/linux/oracle/8/linux-oel.pkr.hcl
builds/linux/oracle/9/linux-oel.pkr.hcl
builds/linux/photon/4/linux-photon.pkr.hcl
builds/linux/photon/5/linux-photon.pkr.hcl
builds/linux/rhel/7/linux-rhel.pkr.hcl
builds/linux/rhel/8/linux-rhel.pkr.hcl
builds/linux/rhel/9/linux-rhel.pkr.hcl
builds/linux/rocky/8/linux-rocky.pkr.hcl
builds/linux/rocky/9/linux-rocky.pkr.hcl
builds/linux/sles/15/linux-sles.pkr.hcl
builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
builds/windows/desktop/10/windows.pkr.hcl
builds/windows/desktop/11/windows.pkr.hcl
builds/windows/server/2019/windows-server.pkr.hcl
builds/windows/server/2022/windows-server.pkr.hcl

Bumps Packer Plugin for Git (`ethanmdavidson/packer-plugin-git`) from v0.4.2 to v0.4.3.

chore(deps): bump packer-plugin-git from v0.4.2 to v0.4.3

---

CHANGELOG.md
README.md
builds/linux/almalinux/8/linux-almalinux.pkr.hcl
builds/linux/almalinux/9/linux-almalinux.pkr.hcl
builds/linux/centos/7/linux-centos.pkr.hcl
builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
builds/linux/debian/11/linux-debian.pkr.hcl
builds/linux/debian/12/linux-debian.pkr.hcl
builds/linux/oracle/8/linux-oel.pkr.hcl
builds/linux/oracle/9/linux-oel.pkr.hcl
builds/linux/photon/4/linux-photon.pkr.hcl
builds/linux/photon/5/linux-photon.pkr.hcl
builds/linux/rhel/7/linux-rhel.pkr.hcl
builds/linux/rhel/8/linux-rhel.pkr.hcl
builds/linux/rhel/9/linux-rhel.pkr.hcl
builds/linux/rocky/8/linux-rocky.pkr.hcl
builds/linux/rocky/9/linux-rocky.pkr.hcl
builds/linux/sles/15/linux-sles.pkr.hcl
builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
builds/windows/desktop/10/windows.pkr.hcl
builds/windows/desktop/11/windows.pkr.hcl
builds/windows/server/2019/windows-server.pkr.hcl
builds/windows/server/2022/windows-server.pkr.hcl

Bumps Packer from v1.9.1 to v1.9.4.

chore(deps): bump packer from v1.9.1 to v1.9.4

---

CHANGELOG.md
README.md
builds/linux/almalinux/8/linux-almalinux.pkr.hcl
builds/linux/almalinux/9/linux-almalinux.pkr.hcl
builds/linux/centos/7/linux-centos.pkr.hcl
builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
builds/linux/debian/11/linux-debian.pkr.hcl
builds/linux/debian/12/linux-debian.pkr.hcl
builds/linux/oracle/8/linux-oel.pkr.hcl
builds/linux/oracle/9/linux-oel.pkr.hcl
builds/linux/photon/4/linux-photon.pkr.hcl
builds/linux/photon/5/linux-photon.pkr.hcl
builds/linux/rhel/7/linux-rhel.pkr.hcl
builds/linux/rhel/8/linux-rhel.pkr.hcl
builds/linux/rhel/9/linux-rhel.pkr.hcl
builds/linux/rocky/8/linux-rocky.pkr.hcl
builds/linux/rocky/9/linux-rocky.pkr.hcl
builds/linux/sles/15/linux-sles.pkr.hcl
builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
builds/windows/desktop/10/windows.pkr.hcl
builds/windows/desktop/11/windows.pkr.hcl
builds/windows/server/2019/windows-server.pkr.hcl
builds/windows/server/2022/windows-server.pkr.hcl

Bumps Packer Plugin for vSphere (`hashicorp/packer-plugin-vsphere`) from  v1.2.0 to v1.2.1.

chore(deps): bump packer-plugin-vsphere from v1.2.0 to v1.2.1

---

CHANGELOG.md
builds/linux/ubuntu/22-04-lts/linux-ubuntu.auto.pkrvars.hcl

Bumps Ubuntu 22.04 from v22.04.2 to v22.04.3.

chore(deps): bump ubuntu from v22.04 to v22.04.3

---

CHANGELOG.md
builds/linux/debian/11/linux-debian.auto.pkrvars.hcl

Bumps Debian from v11.7 to v11.8.

chore(deps): bump debian from v11.7 to v11.8

---

CHANGELOG.md
builds/linux/sles/15/data/autoinst.pkrtpl.hcl
builds/linux/sles/15/linux-sles.auto.pkrvars.hcl

Bumps SLES from v15.4 to v15.5.

chore(deps): bump sles from v15.4 to v15.5

---

builds/windows/desktop/10/windows.auto.pkrvars.hcl

Bumps Windows 10 22H2 to the October 2023 (US English) release.

chore(deps): bump windows 10 22h2 to latest

---

Makefile
docs/getting-started/build.md
docs/getting-started/gitlab-ci-cd.md

Added:
- update-build-script
- update-gitlab-ci
```shell
make update-build-script
make update-gitlab-ci
```

chore: update makefile

---

CHANGELOG.md
docs/getting-started/requirements.md
terraform/vsphere-role/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf
terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-template-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf
terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf
terraform/vsphere-virtual-machine/template-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf

Bumps Terraform from v1.5.0 to v1.6.0.

chore(deps): bump terraform from v1.5.0 to v1.6.0

---

terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/variables.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/variables.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/variables.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/variables.tf
terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization-hcp-packer/variables.tf
terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/variables.tf
terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/variables.tf
terraform/vsphere-virtual-machine/content-library-template-windows-guest-customization-hcp-packer/variables.tf
terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/variables.tf
terraform/vsphere-virtual-machine/template-linux-cloud-init/variables.tf
terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/variables.tf
terraform/vsphere-virtual-machine/template-linux-guest-customization/variables.tf
terraform/vsphere-virtual-machine/template-windows-guest-customization-hcp-packer/variables.tf
terraform/vsphere-virtual-machine/template-windows-guest-customization/variables.tf

Formatting HCL with `terraform fmt -recursive`.

chore: `terraform fmt`

---

.github/workflows/code-analysis.yml

chore(ci): update code analysis

---

CHANGELOG.md
ansible/ansible.cfg
docs/getting-started/requirements.md

- Updates `ansible/ansible.cfg` to use `scp_extra_args = "-O"` by default.

chore: update ansible `scp_extra_args`

---

.gitlab-ci.yml
CHANGELOG.md
README.md
ansible/roles/configure/tasks/debian.yml
ansible/roles/configure/tasks/ubuntu.yml
build.sh
build.yaml
builds/linux/ubuntu/23-10/data/user-data.pkrtpl.hcl
builds/linux/ubuntu/23-10/linux-ubuntu.auto.pkrvars.hcl
builds/linux/ubuntu/23-10/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/23-10/variables.pkr.hcl
docs/getting-started/iso.md
docs/index.md

Adds Ubuntu 23.10.
>**Note**
>Will later be replaced by 24.04 LTS in April 2024.
Closes #725

feat: add ubuntu 23.10

---

CHANGELOG.md
ansible/roles/users/tasks/linux.yml
ansible/roles/users/tasks/photon.yml

Removes redundant Ansible task for users.
Closes #765

chore: remove redundant ansible task

---

builds/linux/almalinux/8/linux-almalinux.pkr.hcl
builds/linux/almalinux/9/linux-almalinux.pkr.hcl
builds/linux/centos/7/linux-centos.pkr.hcl
builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
builds/linux/debian/11/linux-debian.pkr.hcl
builds/linux/debian/12/linux-debian.pkr.hcl
builds/linux/oracle/8/linux-oracle.pkr.hcl
builds/linux/oracle/9/linux-oracle.pkr.hcl
builds/linux/photon/4/linux-photon.pkr.hcl
builds/linux/photon/5/linux-photon.pkr.hcl
builds/linux/rhel/7/linux-rhel.pkr.hcl
builds/linux/rhel/8/linux-rhel.pkr.hcl
builds/linux/rhel/9/linux-rhel.pkr.hcl
builds/linux/rocky/8/linux-rocky.pkr.hcl
builds/linux/rocky/9/linux-rocky.pkr.hcl
builds/linux/sles/15/linux-sles.pkr.hcl
builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/23-10/linux-ubuntu.pkr.hcl

Adds inline comments for the Linux `boot_command` configurations.
Closes #656

chore: add `boot_command` inline comments

---

ansible/roles/clean/tasks/debian.yml
ansible/roles/clean/tasks/photon.yml
ansible/roles/clean/tasks/redhat.yml
ansible/roles/clean/tasks/suse.yml

Fixes the `machine-id` truncate issue introduced in #394.

fix: ansible truncate machine-id

---

ansible/roles/configure/tasks/debian.yml

Updates Ansible playbook for setting SSH keys to regenerate.
Closes #780

fix: debian os family ssh key

---

builds/ansible.pkrvars.hcl.example
builds/build.pkrvars.hcl.example
builds/proxy.pkrvars.hcl.example
builds/rhsm.pkrvars.hcl.example
builds/scc.pkrvars.hcl.example
builds/vsphere.pkrvars.hcl.example
docs/getting-started/configuration.md
docs/getting-started/privileges.md
terraform/vsphere-role/terraform.tfvars.example
terraform/vsphere-role/variables.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/terraform.tfvars.example
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/terraform.tfvars.example
terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/terraform.tfvars.example
terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/terraform.tfvars.example
terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization-hcp-packer/terraform.tfvars.example
terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/terraform.tfvars.example
terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/terraform.tfvars.example
terraform/vsphere-virtual-machine/content-library-template-windows-guest-customization-hcp-packer/terraform.tfvars.example
terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/terraform.tfvars.example
terraform/vsphere-virtual-machine/template-linux-cloud-init/terraform.tfvars.example
terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/terraform.tfvars.example
terraform/vsphere-virtual-machine/template-linux-guest-customization/terraform.tfvars.example
terraform/vsphere-virtual-machine/template-windows-guest-customization-hcp-packer/terraform.tfvars.example
terraform/vsphere-virtual-machine/template-windows-guest-customization/terraform.tfvars.example

Updates the project to use:
-`example.com` as the domain.
- `packer` as the build username.

chore: use example.com

---

docs/getting-started/requirements.md

Updates the documentation for the requirements to direct the reader the the pubic key published by HashiCorp as the source of truth.
Closes #797

docs: update hashicorp pubic key info

---

.gitignore
docs/getting-started/configuration.md

Linux Distributions link doesn't work on live website.
https://vmware-samples.github.io/packer-examples-for-vsphere/getting-started/configuration/#network-customization
Then, ignore built website.

docs: Fix Linux Distributions link

---

.gitlab-ci.yml
build-ci.tmpl

Update build-ci.tmpl to produce working .gitlab-ci.yml.
Yes, resolves #811 
Issue Number: #881

fix: creating/updating .gitlab-ci.yml produces working .gitlab-ci.yml

---

CHANGELOG.md
builds/linux/almalinux/8/linux-almalinux.pkrvars.hcl.example
builds/linux/almalinux/9/linux-almalinux.pkrvars.hcl.example

chore: Update AlmaLinux 8/9 ISOs to latest.
Changelog has been updated.

chore: update AlmaLinux 8/9 ISOs

---

CHANGELOG.md
builds/linux/rhel/8/linux-rhel.pkrvars.hcl.example

Bumps RHEL 8 from v8.8 to v8.9.

chore(deps): bump rhel from v8.8 to v8.9

---

CHANGELOG.md
builds/linux/rhel/9/linux-rhel.pkrvars.hcl.example

Bumps RHEL 9 from v9.2 to v9.3.

chore(deps): bump rhel from v9.2 to v9.3

---

CHANGELOG.md
builds/linux/oracle/8/linux-oracle.pkrvars.hcl.example

Bumps OEL 9 from v8.8 to v8.9.

chore(deps): bump oel from v8.8 to v8.9

---

CHANGELOG.md
builds/linux/oracle/9/linux-oracle.pkrvars.hcl.example

Bumps OEL 9 from v9.2 to v9.3.

chore(deps): bump oel from v9.2 to v9.3

---

CHANGELOG.md
builds/linux/rocky/9/linux-rocky.pkrvars.hcl.example

Bumps Rocky Linux from v9.2 to v9.3.

hore(deps): bump rocky from v9.2 to v9.3

---

CHANGELOG.md
builds/linux/almalinux/8/linux-almalinux.pkr.hcl
builds/linux/almalinux/9/linux-almalinux.pkr.hcl
builds/linux/centos/7/linux-centos.pkr.hcl
builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
builds/linux/debian/11/linux-debian.pkr.hcl
builds/linux/debian/12/linux-debian.pkr.hcl
builds/linux/oracle/8/linux-oracle.pkr.hcl
builds/linux/oracle/9/linux-oracle.pkr.hcl
builds/linux/photon/4/linux-photon.pkr.hcl
builds/linux/photon/5/linux-photon.pkr.hcl
builds/linux/rhel/7/linux-rhel.pkr.hcl
builds/linux/rhel/8/linux-rhel.pkr.hcl
builds/linux/rhel/9/linux-rhel.pkr.hcl
builds/linux/rocky/8/linux-rocky.pkr.hcl
builds/linux/rocky/9/linux-rocky.pkr.hcl
builds/linux/sles/15/linux-sles.pkr.hcl
builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/23-10/linux-ubuntu.pkr.hcl
builds/windows/desktop/10/windows.pkr.hcl
builds/windows/desktop/11/windows.pkr.hcl
builds/windows/server/2019/windows-server.pkr.hcl
builds/windows/server/2022/windows-server.pkr.hcl
docs/getting-started/requirements.md

Bumps Packer Plugin for vSphere (`hashicorp/packer-plugin-vsphere`) from v1.2.1 to v1.2.4.
Will provide the ability to use the `reattach_cdrom` option in v1.2.4.

chore(deps): bump packer-plugin-vsphere from v1.2.1 to v1.2.4

---

CHANGELOG.md
docs/getting-started/requirements.md

Bumps gomplate from v3.11.5 to v3.11.7.

chore(deps): bump gomplate from v3.11.5 to v3.11.7

---

CHANGELOG.md
builds/windows/desktop/10/windows.pkr.hcl
builds/windows/desktop/11/windows.pkr.hcl
builds/windows/server/2019/windows-server.pkr.hcl
builds/windows/server/2022/windows-server.pkr.hcl
docs/getting-started/requirements.md

Bumps Packer Plugin for Windows Updates (`rgl/packer-plugin-windows-update`) from v0.14.3 to v0.15.0

chore(deps): bump packer-plugin-windows-update from v0.14.3 to v0.15.0

---

CHANGELOG.md
builds/linux/almalinux/8/linux-almalinux.pkr.hcl
builds/linux/almalinux/9/linux-almalinux.pkr.hcl
builds/linux/centos/7/linux-centos.pkr.hcl
builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
builds/linux/debian/11/linux-debian.pkr.hcl
builds/linux/debian/12/linux-debian.pkr.hcl
builds/linux/oracle/8/linux-oracle.pkr.hcl
builds/linux/oracle/9/linux-oracle.pkr.hcl
builds/linux/photon/4/linux-photon.pkr.hcl
builds/linux/photon/5/linux-photon.pkr.hcl
builds/linux/rhel/7/linux-rhel.pkr.hcl
builds/linux/rhel/8/linux-rhel.pkr.hcl
builds/linux/rhel/9/linux-rhel.pkr.hcl
builds/linux/rocky/8/linux-rocky.pkr.hcl
builds/linux/rocky/9/linux-rocky.pkr.hcl
builds/linux/sles/15/linux-sles.pkr.hcl
builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/23-10/linux-ubuntu.pkr.hcl
builds/windows/desktop/10/windows.pkr.hcl
builds/windows/desktop/11/windows.pkr.hcl
builds/windows/server/2019/windows-server.pkr.hcl
builds/windows/server/2022/windows-server.pkr.hcl
docs/getting-started/requirements.md

Bumps Packer Plugin for Git (`ethanmdavidson/packer-plugin-git`) from v0.4.3 to v0.6.1.

chore(deps): bump packer-plugin-git from v0.4.3 to v0.6.1

---

CHANGELOG.md
builds/linux/almalinux/8/linux-almalinux.pkr.hcl
builds/linux/almalinux/9/linux-almalinux.pkr.hcl
builds/linux/centos/7/linux-centos.pkr.hcl
builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl
builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
builds/linux/debian/11/linux-debian.pkr.hcl
builds/linux/debian/12/linux-debian.pkr.hcl
builds/linux/oracle/8/linux-oracle.pkr.hcl
builds/linux/oracle/9/linux-oracle.pkr.hcl
builds/linux/photon/4/linux-photon.pkr.hcl
builds/linux/photon/5/linux-photon.pkr.hcl
builds/linux/rhel/7/linux-rhel.pkr.hcl
builds/linux/rhel/8/linux-rhel.pkr.hcl
builds/linux/rhel/9/linux-rhel.pkr.hcl
builds/linux/rocky/8/linux-rocky.pkr.hcl
builds/linux/rocky/9/linux-rocky.pkr.hcl
builds/linux/sles/15/linux-sles.pkr.hcl
builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
builds/linux/ubuntu/23-10/linux-ubuntu.pkr.hcl
builds/windows/desktop/10/windows.pkr.hcl
builds/windows/desktop/11/windows.pkr.hcl
builds/windows/server/2019/windows-server.pkr.hcl
builds/windows/server/2022/windows-server.pkr.hcl
docs/getting-started/requirements.md

Bumps Packer (`hashicorp/packer`) from v1.9.4 to v1.10.0.

chore(deps): bump packer from v1.9.4 to v1.10.0

---

CHANGELOG.md
docs/getting-started/requirements.md
terraform/vsphere-role/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf
terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-template-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf
terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf
terraform/vsphere-virtual-machine/template-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf

Bumps Terraform from v1.6.0 to v1.7.1.

chore(deps): bump terraform from v1.6.0 to v1.7.1

---

CHANGELOG.md
terraform/vsphere-role/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf
terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-template-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf
terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf
terraform/vsphere-virtual-machine/template-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf

Bumps Terraform Provider for vSphere (`hashicorpn/terraform-provider-vsphere`)from v2.5.1 to v2.6.1.

chore(deps): bumperraform-provider-vsphere from v2.5.1 to v2.6.1

---

CHANGELOG.md
terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/content-library-template-windows-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/versions.tf
terraform/vsphere-virtual-machine/template-windows-guest-customization-hcp-packer/versions.tf

Bumps Terraform Provider for HCP (`hashicorpn/terraform-provider-hcp`) from  v0.74.1 to v0.81.0.

chore(deps): bumperraform-provider-hcp from v0.74.1 to v0.81.0

---

ansible/roles/configure/tasks/debian.yml

Ref: #https://github.com/vmware-samples/packer-examples-for-vsphere/pull/195#issuecomment-1219932995
Closes #815

fix: debian guest os identifier override

---

.gitlab-ci.yml
CHANGELOG.md
README.md
build.sh
build.yaml
builds/windows/server/2025/data/autounattend.pkrtpl.hcl
builds/windows/server/2025/variables.pkr.hcl
builds/windows/server/2025/windows-server.pkr.hcl
builds/windows/server/2025/windows-server.pkrvars.hcl.example
docs/index.md

This PR adds support for Windows Server 2025 Insiders Previews to enable customers to try/test these releases.
Resolves: #833 
Issue Number: #833
Updated the changelog.

feat: add support for Windows Server 2025 Insiders Preview

---

builds/linux/almalinux/8/linux-almalinux.pkr.hcl
builds/linux/almalinux/9/linux-almalinux.pkr.hcl
builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl
builds/linux/oracle/9/linux-oracle.pkr.hcl
builds/linux/rhel/9/linux-rhel.pkr.hcl
builds/linux/rocky/9/linux-rocky.pkr.hcl
builds/linux/sles/15/linux-sles.pkr.hcl

Fix typo in the `playbook_file` variable.
Issue introduced in PR 801

fix: typo in playbook_file
