builds/windows/windows-server-2019/windows-server-2019.pkr.hcl
The following error message is observed:
Starting the HashiCorp Packer build ...
Error: Unsupported argument
on windows-server-2019.pkr.hcl line 562:
(source code not available)
An argument named "iso_checksu" is not expected here. Did you mean
"iso_checksum"?
=> Typo fix in windows-server-2019.pkr.hcl

builds/linux/almalinux-8/linux-almalinux.pkr.hcl, builds/linux/almalinux-8/variables.pkr.hcl, builds/linux/centos-linux-8/linux-centos-linux.pkr.hcl, builds/linux/centos-linux-8/variables.pkr.hcl, builds/linux/centos-stream-8/linux-centos-stream.pkr.hcl, builds/linux/centos-stream-8/variables.pkr.hcl, builds/linux/photon-4/linux-photon.pkr.hcl, builds/linux/photon-4/variables.pkr.hcl, builds/linux/redhat-linux-8/linux-redhat-linux.pkr.hcl, builds/linux/redhat-linux-8/variables.pkr.hcl, builds/linux/rocky-linux-8/linux-rocky-linux.pkr.hcl, builds/linux/rocky-linux-8/variables.pkr.hcl, builds/linux/ubuntu-server-18-04-lts/linux-ubuntu-server.pkr.hcl, builds/linux/ubuntu-server-18-04-lts/variables.pkr.hcl, builds/linux/ubuntu-server-20-04-lts/linux-ubuntu-server.pkr.hcl, builds/linux/ubuntu-server-20-04-lts/variables.pkr.hcl, builds/windows/windows-server-2016/variables.pkr.hcl, builds/windows/windows-server-2016/windows-server.pkr.hcl, builds/windows/windows-server-2019/variables.pkr.hcl, builds/windows/windows-server-2019/windows-server.pkr.hcl, builds/windows/windows-server-2022/variables.pkr.hcl, builds/windows/windows-server-2022/windows-server.pkr.hcl
Add dynamic for `content_library_destination` block.
Issue Number: #43 
-  Verified by maintainer - @tenthirtyam 
=> Make content_library_destination optional

builds/linux/almalinux-8/linux-almalinux.pkr.hcl, builds/linux/centos-linux-8/linux-centos-linux.pkr.hcl, builds/linux/centos-stream-8/linux-centos-stream.pkr.hcl, builds/linux/redhat-linux-8/linux-redhat-linux.pkr.hcl, builds/linux/rocky-linux-8/linux-rocky-linux.pkr.hcl
Updated the `boot_command` for rhel/variants to use `inst.ks=` instead of `ks=`.
Please describe: Replacing deprecated `ks=` command.
Updated the `boot_command` for rhel/variants to use `inst.ks=` instead of `ks=`.
=> Update boot_command for rhel/variants

builds/linux/ubuntu-server-20-04-lts/http/user-data.pkrtpl.hcl
- Replace `ens33` by `ens192` because the network adapter is `vmxnet3`.
- Remove packages update from `user-data` because the update is managed by the script.
Ubuntu 20.04 user-data
=> Fix Ubuntu 20.04 user-data

README.md, build.sh, builds/linux/almalinux-8/linux-almalinux.pkr.hcl, builds/linux/almalinux-8/variables.pkr.hcl, builds/linux/centos-linux-8/linux-centos-linux.pkr.hcl, builds/linux/centos-linux-8/variables.pkr.hcl, builds/linux/centos-stream-8/linux-centos-stream.pkr.hcl, builds/linux/centos-stream-8/variables.pkr.hcl, builds/linux/photon-4/linux-photon.pkr.hcl, builds/linux/photon-4/variables.pkr.hcl, builds/linux/redhat-linux-8/linux-redhat-linux.pkr.hcl, builds/linux/redhat-linux-8/variables.pkr.hcl, builds/linux/rocky-linux-8/linux-rocky-linux.pkr.hcl, builds/linux/rocky-linux-8/variables.pkr.hcl, builds/linux/ubuntu-server-18-04-lts/linux-ubuntu-server.pkr.hcl, builds/linux/ubuntu-server-18-04-lts/variables.pkr.hcl, builds/linux/ubuntu-server-20-04-lts/linux-ubuntu-server.pkr.hcl, builds/linux/ubuntu-server-20-04-lts/variables.pkr.hcl, builds/proxy.pkrvars.hcl
Add support of `ssh_proxy_*` variables for Linux images.
https://github.com/rainpole/packer-vsphere/discussions/39
=> Support ssh_proxy_* variables for Linux images

builds/linux/ubuntu-server-20-04-lts/http/user-data.pkrtpl.hcl
Reverting `ens192` to `ens33` from  PR #53 to address #56.
The use of ens192 is causing IPs to change mid-build. Reverting to `ens33` to resolve the issue in `main`.  We can research more if `ens192` is required.
Issue Number: #56 
Closes: #56 
=> Revert to ens33 for Ubuntu 20.04 LTS

builds/linux/photon-4/data/ks.pkrtpl.hcl, builds/linux/photon-4/linux-photon.auto.pkrvars.hcl, builds/linux/photon-4/linux-photon.pkr.hcl
Update PhotonOS to `efi-secure`
- Update `bootmode` to `efi`
- Update `vm_firmware` to `efi-secure`
- Update `boot_command`
=> Update PhotonOS to `efi-secure`

builds/linux/almalinux-8/data/ks.pkrtpl.hcl, builds/linux/centos-linux-8/data/ks.pkrtpl.hcl, builds/linux/centos-stream-8/data/ks.pkrtpl.hcl, builds/linux/photon-4/data/ks.pkrtpl.hcl, builds/linux/rocky-linux-8/data/ks.pkrtpl.hcl
Adds Ansible package and dependencies to RHEL-variants and PhotonOS.
Adds Ansible package and dependencies to RHEL-variants and PhotonOS.
Issue Number: #54 
=> Add ansible to rhel-variants and photonos

README.md, build.sh, builds/linux/almalinux-8/linux-almalinux.auto.pkrvars.hcl, builds/linux/almalinux-8/linux-almalinux.pkr.hcl, builds/linux/centos-linux-8/linux-centos-linux.auto.pkrvars.hcl, builds/linux/centos-linux-8/linux-centos-linux.pkr.hcl, builds/linux/centos-stream-8/linux-centos-stream.auto.pkrvars.hcl, builds/linux/centos-stream-8/linux-centos-stream.pkr.hcl, builds/linux/photon-4/linux-photon.auto.pkrvars.hcl, builds/linux/photon-4/linux-photon.pkr.hcl, builds/linux/redhat-linux-8/linux-redhat-linux.auto.pkrvars.hcl, builds/linux/redhat-linux-8/linux-redhat-linux.pkr.hcl, builds/linux/rocky-linux-8/linux-rocky-linux.auto.pkrvars.hcl, builds/linux/rocky-linux-8/linux-rocky-linux.pkr.hcl, builds/linux/ubuntu-server-18-04-lts/linux-ubuntu-server.auto.pkrvars.hcl, builds/linux/ubuntu-server-18-04-lts/linux-ubuntu-server.pkr.hcl, builds/linux/ubuntu-server-20-04-lts/linux-ubuntu-server.auto.pkrvars.hcl, builds/linux/ubuntu-server-20-04-lts/linux-ubuntu-server.pkr.hcl, builds/windows/windows-server-2016/windows-server.auto.pkrvars.hcl, builds/windows/windows-server-2016/windows-server.pkr.hcl, builds/windows/windows-server-2019/windows-server.auto.pkrvars.hcl, builds/windows/windows-server-2019/windows-server.pkr.hcl, builds/windows/windows-server-2022/windows-server.auto.pkrvars.hcl, builds/windows/windows-server-2022/windows-server.pkr.hcl
Use the flexibiliy of `path.cwd` and `path.root` when using `build.sh`.
See https://www.packer.io/docs/templates/hcl_templates/path-variables
Following updates have been done:
- remove `../../..` from everywhere (that ease a refactoring if necessary)
- replace `path.cwd` by `path.root` to access files data directory
- replace `../../certificates` by `${path.cwd}/certificates` to access certificates
- replace `../../manifests` by `${path.cwd}/manifests` to access manifests
- replace `../../scripts` by `${path.cwd}/scripts` to access scripts
So, the `packer` command could be launched from whatever directory that contains custom `certificates`, `scripts` and output `manifests`.
Enable …
=> Allow Packer to be launched from any directory

README.md, builds/common.pkrvars.hcl.example, builds/linux/almalinux-8/linux-almalinux.pkr.hcl, builds/linux/almalinux-8/variables.pkr.hcl, builds/linux/centos-linux-8/linux-centos-linux.pkr.hcl, builds/linux/centos-linux-8/variables.pkr.hcl, builds/linux/centos-stream-8/linux-centos-stream.pkr.hcl, builds/linux/centos-stream-8/variables.pkr.hcl, builds/linux/photon-4/linux-photon.pkr.hcl, builds/linux/photon-4/variables.pkr.hcl, builds/linux/redhat-linux-8/linux-redhat-linux.pkr.hcl, builds/linux/redhat-linux-8/variables.pkr.hcl, builds/linux/rocky-linux-8/linux-rocky-linux.pkr.hcl, builds/linux/rocky-linux-8/variables.pkr.hcl, builds/linux/ubuntu-server-18-04-lts/linux-ubuntu-server.pkr.hcl, builds/linux/ubuntu-server-18-04-lts/variables.pkr.hcl, builds/linux/ubuntu-server-20-04-lts/linux-ubuntu-server.pkr.hcl, builds/linux/ubuntu-server-20-04-lts/variables.pkr.hcl
Adds the option define a specific IPv4 address from your host for Packer's HTTP Server.
Modify the `common_http_ip `variable from `null` to a `string` value. 
For example: `common_http_ip = "172.16.11.254"`
- Adds `common_http_ip` to `common.pkrvars.hcl.example`. Default, `null`.
- Adds `common_http_ip` to `variables.pkr.hcl' for Linux distributions.
- Adds `http_ip` to the`*.pkr.hcl` for Linux distributions.
- Updates the project documentation for `common.pkrvars.hcl` settings. …
=> Add HTTP IP address option

builds/windows/windows-server-2016/data/autounattend.pkrtpl.hcl, builds/windows/windows-server-2019/data/autounattend.pkrtpl.hcl, builds/windows/windows-server-2022/data/autounattend.pkrtpl.hcl
Fix typo in `autounattend.pkrtpl.hcl`
Fixes typo for `<SystemLocale/>`value in `autounattend.pkrtpl.hcl`
Issue Number: #86 
Closes: #86 
=> Fix typo in `autounattend.pkrtpl.hcl`

README.md, build.sh, builds/windows/windows-10/data/autounattend.pkrtpl.hcl, builds/windows/windows-10/variables.pkr.hcl, builds/windows/windows-10/windows.auto.pkrvars.hcl, builds/windows/windows-10/windows.pkr.hcl
Implement Windows 10 Pro image
- Add `windows-10` folder
- Copy `windows-server-2022` content to `windows-10` as base
- Update `variables.pkr.hcl`
- Remove `vm_guest_os_member` variable, because only Windows
- Remove `vm_guest_os_ed*` and `vm_guest_os_exp*` variables, because support only Windows 10 Pro
- Create `vm_inst_os_language` and `vm_inst_os_keyboard` variables, because Windows 10 installer contains only one language. 
- Update `autounattended.pkrtpl.hcl`
- Use `vm_inst_os_language` and `vm_inst_os_keyboard` variables on installer settings component
- Add guest settings component for guest locale
Issue Number: #87 
**Test and Documentation …
=> Add Windows 10 Professional

builds/windows/windows-10/data/autounattend.pkrtpl.hcl, builds/windows/windows-server-2016/data/autounattend.pkrtpl.hcl, builds/windows/windows-server-2019/data/autounattend.pkrtpl.hcl, builds/windows/windows-server-2022/data/autounattend.pkrtpl.hcl
Remove <ComputerName/> from autounattend.pkrtpl.hcl
- Removing `<ComputerName/>` from `autounattend.pkrtpl.hcl`
- Allows Windows OS to generate a name based off up to the first 7char of the organization name, a hyphen, and a 7char auto-generated string. (e.g. `RAINPOL-G8T2QG1`)
Issue Number: #90 
Closes: #90 
=> Remove `<ComputerName/>` from `autounattend.pkrtpl.hcl`

builds/linux/ubuntu-server-20-04-lts/linux-ubuntu-server.auto.pkrvars.hcl, builds/linux/ubuntu-server-20-04-lts/linux-ubuntu-server.pkr.hcl, builds/linux/ubuntu-server-20-04-lts/variables.pkr.hcl
Update Ubuntu 20.04 LTS to `efi-secure`
- Update `vm_firmware` to `efi-secure` in `linux-photon.auto.pkrvars.hcl`
- Update `vm_firmware` default to `efi-secure` in `variables.hcl`
- Update `boot_command` in `linux-ubuntu-servrer.pkr.hcl` 
=> Update Ubuntu 20.04 LTS to `efi-secure`

README.md, builds/linux/photon-4/linux-photon.auto.pkrvars.hcl
Revert to Photon OS 4.0 GA from 4.0 Revision 1
Reverting to Photon OS 4.0 GA from 4.0 Revision 1 due to #94. 
Will open an issue with vmware/photon to determine the cause of the issue in Rev1.
Issue Number: #94 
=> Revert to Photon OS 4.0 GA from 4.0 Revision 1

builds/linux/almalinux-8/data/ks.pkrtpl.hcl, builds/linux/centos-linux-8/data/ks.pkrtpl.hcl, builds/linux/centos-stream-8/data/ks.pkrtpl.hcl, builds/linux/rocky-linux-8/data/ks.pkrtpl.hcl
Removes `sudo` from the `ks.pkrtpl.hcl` for rhel-derivatives.
Remove `sudo` from the `ks.pkrtpl.hcl` for post-installation command (not required.)]
=> Remove `sudo` from the `ks.pkrtpl.hcl` for rhel-derivatives

builds/linux/ubuntu-server-20-04-lts/data/user-data.pkrtpl.hcl, scripts/linux/ubuntu-server-2x.sh
Enables the cloud-init  `VMware` data source on Ubuntu 20.04 LTS with cloud-init 21.3+. (canonical/cloud-init 977)
Enables the cloud-init `VMware` data source on Ubuntu 20.04 LTS with cloud-init 21.3+. (canonical/cloud-init 977)
=> Enable cloud-init `VMware` data source on Ubuntu 20.04 

builds/linux/almalinux/8/linux-almalinux.pkr.hcl, builds/linux/centos/7/linux-centos.pkr.hcl, builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl, builds/linux/centos/8/linux-centos.pkr.hcl, builds/linux/rhel/7/linux-rhel.pkr.hcl, builds/linux/rhel/8/linux-rhel.pkr.hcl, builds/linux/rocky/8/linux-rocky.pkr.hcl
Updates `"up"` to `"<up"` in the `boot_command` for RHEL and derivatives. #178
Closes #178
=> fix: :wrench: Correct `boot_command` for RHEL and derivatives

builds/windows/server/2022/windows-server.auto.pkrvars.hcl
Fixes the `iso_checksum_value` value for Windows Server 2022
=> bug: Fix `iso_checksum_value` value

CHANGELOG.md, builds/linux/almalinux/8/linux-almalinux.pkr.hcl, builds/linux/centos/7/linux-centos.pkr.hcl, builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl, builds/linux/centos/8/linux-centos.pkr.hcl, builds/linux/photon/4/linux-photon.pkr.hcl, builds/linux/rhel/7/linux-rhel.pkr.hcl, builds/linux/rhel/8/linux-rhel.pkr.hcl, builds/linux/rocky/8/linux-rocky.pkr.hcl, builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl, builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl, builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
Fix issue GH-197 as discussed in the issue.
Closes #197
=> fix: gh-197

CHANGELOG.md, builds/windows/desktop/10/variables.pkr.hcl, builds/windows/desktop/10/windows.auto.pkrvars.hcl, builds/windows/desktop/10/windows.pkr.hcl, builds/windows/desktop/11/variables.pkr.hcl, builds/windows/desktop/11/windows.auto.pkrvars.hcl, builds/windows/desktop/11/windows.pkr.hcl
Adds options for setting the number of video displays and the size for the video memory for both Windows 11 and 10. The ability to set the number of displays [was added](https://github.com/hashicorp/packer-plugin-vsphere/pull/201) in  `v1.0.6` of `packer-plugin-vsphere`.
```hcl
variable "vm_video_mem_size" {
type        = number
description = "The size for the video memory in KB. (e.g. 4096)"
default     = 4096
}
variable "vm_video_displays" {
type        = number
description = "The number of video displays. (e.g. 1)"
default     = 1
}
````
```hcl
source "vsphere-iso" "windows-desktop" {
... # other configurations
video_ram            = var.vm_video_mem_size
displays             = var.vm_video_displays
... # other configurations
}
```
```hcl
// Virtual Machine Hardware Settings
... # …
```
=> feat: Add option for `video_ram` and `displays`

builds/linux/almalinux/8/linux-almalinux.pkr.hcl, builds/linux/almalinux/9/linux-almalinux.pkr.hcl, builds/linux/centos/7/linux-centos.pkr.hcl, builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl, builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl, builds/linux/photon/4/linux-photon.pkr.hcl, builds/linux/rhel/7/linux-rhel.pkr.hcl, builds/linux/rhel/8/linux-rhel.pkr.hcl, builds/linux/rhel/9/linux-rhel.pkr.hcl, builds/linux/rocky/8/linux-rocky.pkr.hcl, builds/linux/rocky/9/linux-rocky.pkr.hcl, builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl, builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl, builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl
Set the Ansible user to run under the context of the `var.build_username` on the image.
Closes #216
=> fix: Set user context for Ansible provisioner

README.md, ansible/roles/base/tasks/main.yml, ansible/roles/base/tasks/sles.yml, ansible/roles/clean/tasks/main.yml, ansible/roles/clean/tasks/sles.yml, ansible/roles/configure/tasks/main.yml, ansible/roles/configure/tasks/sles.yml, ansible/roles/users/tasks/main.yml, build.sh, build.yaml, builds/linux/sles/15/data/autoinst.pkrtpl.hcl, builds/linux/sles/15/linux-sles.auto.pkrvars.hcl, builds/linux/sles/15/linux-sles.pkr.hcl, builds/linux/sles/15/variables.pkr.hcl, builds/scc.pkrvars.hcl.example, set-envvars.sh
Adds support for SUSE Enterprise Linux 15 machine image.
- 15.3 / SP3 for initial introduction
- HTTP-based kickstart only. 
Will note in the Release Notes and `CHANGELOG.md`
Closes: #199
=> enhance: Add support for SLES 15 (SP3) machine image

builds/windows/desktop/10/windows.auto.pkrvars.hcl, builds/windows/desktop/11/windows.auto.pkrvars.hcl, builds/windows/server/2022/windows-server.auto.pkrvars.hcl
Update the following based on August 2022 updates:
Released: 8/16/2022
SHA256: `880C7F6E7818B396EE66AF8B1A3D86BB57810EA2FD6AE447F4D5124340076609`
File name: `en-us_windows_server_2022_updated_aug_2022_x64_dvd_8b65e57f.iso`
Released: 8/16/2022
SHA256: `8B5FE1C2FDB14BD9561460D976E9040FBB7B3CEEDF9DD20FFA1CD9984C6286A0`
File name: `en-us_windows_11_business_editions_version_21h2_updated_aug_2022_x64_dvd_50c9cab3.iso`
Released: 8/16/2022
SHA256: `BC0278961FDB5219C647C20119734389EDC43BB3933B3BE804F8B9C5B2A45A1B`
File name: `en-us_windows_10_business_editions_version_21h1_updated_aug_2022_x64_dvd_b3dc85d2.iso`
Closes: #250
=> chore(deps): bump .iso to August 2022 revisions for Windows guest operating systems

builds/linux/debian/11/data/ks.pkrtpl.hcl, builds/linux/debian/11/linux-debian.pkr.hcl
Debian 11 was introduced to the project in the v22.08 release with only support for HTTP-based deployment only.
This PR will add the enhancement for disk-based deployment support and fix issue #261 as discussed with @tenthirtyam in comments.
- Resolves #261 
The `boot_command` and the `preseed/early_command` are determined based on the configuration in the common_data_source variable.
Here is the output of the whole boot sequence with the `common_data_source` variable set to `disk`:
And here is a screenshot of the boot command with the `common_data_source` variable set to `http`:
=> fix: add support for disk-based deployment mode for Debian 11

builds/linux/sles/15/linux-sles.pkr.hcl
Adds support for disk-based deployment mode for SLES 15.
Closes #260
=> fix: add support for disk-based deployment mode for SLES 15

builds/windows/desktop/10/windows.auto.pkrvars.hcl
Bumps Windows 10 to the 21H2 September 2022 release.
Signed-off-by: Ryan Johnson johnsonryan@vmware.com
=> chore(deps): bump windows 10 to 21h2 september 2022

builds/windows/desktop/11/windows.auto.pkrvars.hcl, scripts/windows/windows-init.ps1
Bumps Windows 11 to the 22H2 September 2022 release.
In addition, in Windows 11 22H2 the value for the OS image has changed from `Windows 10 Pro` to `Windows 11 Pro`.
```xml
<ImageInstall>
<OSImage>
<InstallFrom>
<MetaData wcm:action="add">
<Key>/IMAGE/NAME</Key>
<Value>${vm_inst_os_image}</Value>
</MetaData>
</InstallFrom>
<InstallTo>
<DiskID>0</DiskID>
<PartitionID>4</PartitionID>
</InstallTo>
</OSImage>
</ImageInstall>
```
Signed-off-by: Ryan Johnson johnsonryan@vmware.com
=> chore(deps): bump windows 11 to 22h2 september 2022

README.md, terraform/vsphere-role/terraform.tfvars.example
Adds missing privilege to `README.md` configuration section and the Terraform example for a custom vSphere role.
`Virtual Machine > Configuration > Modify device settings` = `VirtualMachine.Config.EditDevice`
Closes #337
=> fix: update custom role privileges

builds/linux/centos/9-stream/linux-centos-stream.auto.pkrvars.hcl
Bumps CentOS Stream 9 to the November 2022 release.
=> chore(deps): bump centos stream 9 to latest

builds/windows/server/2022/windows-server.auto.pkrvars.hcl
Bumps Windows Server 2022 to October 2022 release.
=> chore(deps): bump windows server 2022 to latest

README.md
You just want to append the algorihm ```ssh-rsa``` instead of replacing already existing algorithms. 
Otherwise services like GitHub might complain about unsupported algorithms.
```
➜ git pull
ERROR: You're using an RSA key with SHA-1, which is no longer allowed. Please use a newer client or a different key type.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```
=> docs: update syntax to append algorithm

README.md, builds/linux/almalinux/8/linux-almalinux.pkr.hcl, builds/linux/almalinux/9/linux-almalinux.pkr.hcl, builds/linux/centos/7/linux-centos.pkr.hcl, builds/linux/centos/8-stream/linux-centos-stream.pkr.hcl, builds/linux/centos/9-stream/linux-centos-stream.pkr.hcl, builds/linux/debian/11/linux-debian.pkr.hcl, builds/linux/photon/4/linux-photon.pkr.hcl, builds/linux/rhel/7/linux-rhel.pkr.hcl, builds/linux/rhel/8/linux-rhel.pkr.hcl, builds/linux/rhel/9/linux-rhel.pkr.hcl, builds/linux/rocky/8/linux-rocky.pkr.hcl, builds/linux/rocky/9/linux-rocky.pkr.hcl, builds/linux/sles/15/linux-sles.pkr.hcl, builds/linux/ubuntu/18-04-lts/linux-ubuntu.pkr.hcl, builds/linux/ubuntu/20-04-lts/linux-ubuntu.pkr.hcl, builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl, builds/windows/desktop/10/windows.pkr.hcl, builds/windows/desktop/11/windows.pkr.hcl, builds/windows/server/2019/windows-server.pkr.hcl, builds/windows/server/2022/windows-server.pkr.hcl
The build already has the timestamp as ```build_date```.  Consider using the current Git branch / tag as ```build_version```, so that it is clear on which code base the image was built. 
Closes #388
=> refactor: Use Git branch / tag for versioning

README.md, ansible/ansible.cfg
Adds `HostKeyAlgorithms=+ssh-rsa` and `PubkeyAcceptedKeyTypes=+ssh-rsa` as extra arguments for Ansible.
This will set these parameters automatically instead of assuming that the user has read the current documented requirements. 
I have tested this for Debian 11 and Ubuntu Server 22.04 LTS. VMware Photon OS 4 did not get pass the boot loader.
=> feat: Allow SSH authentication with RSA keys

builds/linux/ubuntu/20-04-lts/data/user-data.pkrtpl.hcl, builds/linux/ubuntu/22-04-lts/data/user-data.pkrtpl.hcl
The ```uri``` should not contain a country code like ```us```. Otherwise the GeoIP lookup does not work. 
```
deb http://us.archive.ubuntu.com/ubuntu jammy main restricted
vs
deb http://de.archive.ubuntu.com/ubuntu jammy main restricted
```
https://github.com/canonical/subiquity/blob/main/documentation/autoinstall-reference.md?plain=1#L214
=> fix: remove country code for ubuntu

README.md
Updates the `README.md` to demonstrate the use of 521 bits with ssh-keygen. Valid lengths are 256, 384, or 521.
Closes #442
=> fix: update `README.md`

builds/windows/desktop/10/windows.auto.pkrvars.hcl
Bumps Windows 10 to the 22H2 December 2022 release.
=> chore(deps): bump windows 10 to 22h2 to latest

builds/windows/desktop/11/windows.auto.pkrvars.hcl
Bumps Windows 11 to the 22H2 December 2022 release.
=> chore(deps): bump windows 11 to 22h2 latest

.gitignore
1. Updated .gitignore to correctly ignore  `.vmdk`, `.nvram`, `.ovf` and `.mf` files.
2. Added `tfplan` files to .gitignore, also added additional ignores here to match the [GitHub template](https://github.com/github/gitignore/blob/main/Terraform.gitignore).
Resolves #472
=> feat: update .gitignore terraform/artifacts

CHANGELOG.md, terraform/vsphere-role/versions.tf, terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/versions.tf, terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf, terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/versions.tf, terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf, terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization-hcp-packer/versions.tf, terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf, terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/versions.tf, terraform/vsphere-virtual-machine/content-library-template-windows-guest-customization-hcp-packer/versions.tf, terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/versions.tf, terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf, terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/versions.tf, terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf, terraform/vsphere-virtual-machine/template-windows-guest-customization-hcp-packer/versions.tf, terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf
Bumps Terraform Provider for VMware vSphere (`hashicorp/vsphere`) from v2.2.0 to v2.3.1.
=> chore(deps): bump hashcorp/vsphere from v2.2.0 to v2.3.1

CHANGELOG.md, terraform/vsphere-role/versions.tf, terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/versions.tf, terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf, terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/versions.tf, terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf, terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization-hcp-packer/versions.tf, terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf, terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/versions.tf, terraform/vsphere-virtual-machine/content-library-template-windows-guest-customization-hcp-packer/versions.tf, terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/versions.tf, terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf, terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/versions.tf, terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf, terraform/vsphere-virtual-machine/template-windows-guest-customization-hcp-packer/versions.tf, terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf
Bumps Terraform Provider for VMware vSphere (`hashicorp/vsphere`) from v2.3.1 to v2.4.0
=> chore(deps): bump hashcorp/vsphere from v2.3.1 to v2.4.0

CHANGELOG.md, builds/linux/ubuntu/20-04-lts/linux-ubuntu.auto.pkrvars.hcl
Bumps Ubuntu 20.04 from v20.04.5 to v20.04.6.
=> chore(deps): bump ubuntu from v20.04.5 to v20.04.6

CHANGELOG.md, builds/linux/centos/8-stream/linux-centos-stream.auto.pkrvars.hcl
Bumps CentOS Stream 8 checksum to the latest June 2023 release.
=> chore(deps): bump centos stream 8 to latest

CHANGELOG.md, builds/linux/debian/11/linux-debian.auto.pkrvars.hcl
Bumps Debian 11 from v11.6 to v11.7.
=> chore(deps): bump debian from v11.6 to v11.7

CHANGELOG.md, builds/windows/desktop/11/windows.auto.pkrvars.hcl
Bumps Windows 11 22H2 to the May 2023 (US English) release.
=> chore(deps): bump windows 11 22h2 to latest

CHANGELOG.md, builds/windows/desktop/10/windows.auto.pkrvars.hcl
Bumps Windows 10 22H2 to May 2023 (US English) release.
=> chore(deps): bump windows 10 22h2 to latest

CHANGELOG.md, builds/windows/desktop/11/windows.auto.pkrvars.hcl
Windows 11 22H2 to the May 2023 (US English) release.
=> fix(deps): bump windows 11 22h2 to latest

CHANGELOG.md, README.md, build.sh, build.yaml, builds/linux/debian/12/data/ks.pkrtpl.hcl, builds/linux/debian/12/linux-debian.auto.pkrvars.hcl, builds/linux/debian/12/linux-debian.pkr.hcl, builds/linux/debian/12/variables.pkr.hcl
Adds Debian 12 (Bookworm) to the project.
=> feat: add debian 12

CHANGELOG.md, builds/windows/desktop/10/windows.auto.pkrvars.hcl, builds/windows/desktop/11/windows.auto.pkrvars.hcl, builds/windows/server/2019/windows-server.auto.pkrvars.hcl, builds/windows/server/2022/windows-server.auto.pkrvars.hcl
Removes the installation of Chocolatey from the Microsoft Windows guest operating system builds. .Net 4.8 is required before installation. This can be managed by the user instead of this project.
Closes #585
=> refactor: remove chocolatey from windows builds

CHANGELOG.md, builds/linux/debian/11/linux-debian.pkr.hcl, builds/linux/debian/12/linux-debian.pkr.hcl
This PR fixes issue of SSHing into the VM while creating an debian based OVF. Whitout this fix user gets error 'Timeout waiting for SSH' as SSH credentials could not be set properly on the host. The changes done in this PR are already present for other linux based OSes in their respective linux-*.pkr.hcl file. (e.g. builds/centos/7/linux-centos.pkr.hcl)
=> fix: use `build_password` and `build_password_encrypted` for debian

.gitlab-ci.yml, CHANGELOG.md, README.md, build-ci.tmpl
Add templated way of generating a `.gitlab-ci.yml` file to enable a GitLab CI/CD pipeline to build the Packer templates
This change:
- Adds new `build-ci.tmpl` that can be used to crete/update `.gitlab-ci.yml` file
- Adds example `.gitlab.yml` file.
- Adds section to `README.md` describing how to use `build-ci.tmpl` that can be used to create/update `.gitlab-ci.yml` file.
Closes #674
=> feat: add templated `.gitlab-ci.yml` method

CHANGELOG.md, builds/linux/debian/12/linux-debian.pkr.hcl
Fix Debian 12 mount of  `/dev/sr1` with  `http` data source.
Closes #673
=> fix: debian 12 mount of  `/dev/sr1` with  `http` data source

.gitlab-ci.yml, build-ci.tmpl
The packer validate step in the new `.gitlab-ci.yml` does not include references to the necessary `.pkrvar.hcl` files and that breaks the GitLab CI/CD pipeline.
This PR add the reference to the necessary `.pkrvar.hcl` files.
- Resolves #701 
Issue Number: #701
=> Fix for issue #701

CHANGELOG.md, README.md, build.sh, build.tmpl, build.yaml
- Adds `--help` / `-h` option to `./build.sh` for help.
- Adds `--debug` / `-d` option to `./build.sh` for debug mode.
- Updates `README.md`.
Closes #697
=> feat: add debug

CHANGELOG.md, terraform/vsphere-role/versions.tf, terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init-hcp-packer/versions.tf, terraform/vsphere-virtual-machine/content-library-ovf-linux-cloud-init/versions.tf, terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization-hcp-packer/versions.tf, terraform/vsphere-virtual-machine/content-library-ovf-linux-guest-customization/versions.tf, terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization-hcp-packer/versions.tf, terraform/vsphere-virtual-machine/content-library-ovf-windows-guest-customization/versions.tf, terraform/vsphere-virtual-machine/content-library-template-linux-guest-customization-hcp-packer/versions.tf, terraform/vsphere-virtual-machine/content-library-template-windows-guest-customization-hcp-packer/versions.tf, terraform/vsphere-virtual-machine/template-linux-cloud-init-hcp-packer/versions.tf, terraform/vsphere-virtual-machine/template-linux-cloud-init/versions.tf, terraform/vsphere-virtual-machine/template-linux-guest-customization-hcp-packer/versions.tf, terraform/vsphere-virtual-machine/template-linux-guest-customization/versions.tf, terraform/vsphere-virtual-machine/template-windows-guest-customization-hcp-packer/versions.tf, terraform/vsphere-virtual-machine/template-windows-guest-customization/versions.tf
Bumps Terraform Provider for VMware vSphere (`hashicorp/vsphere`) from v2.4.0 to v2.5.1.
=> chore(deps): bump hashcorp/vsphere from v2.4.0 to v2.5.1

builds/linux/ubuntu/23-10/linux-ubuntu.pkr.hcl
Re-add missing galaxy_file and galaxy_froce_with_deps entries from Ubuntu Server 23.10 linux-ubuntu.pkr.hcl file.
Ubuntu Server 23.10 failing due ansible collection(s) missing
For some reason, the Ubuntu 23.10 `linux-ubuntu.pkr.hcl` file was missing `galaxy_file` and `galaxy_force_with_deps` from the ansible provisioner section.
Resolves #778 
Issue Number: #778
=> Fix issue-778

ansible/roles/configure/tasks/debian.yml
Enhances the Ansible task to use `copy` versus `lineinfile` to create `/etc/rc.local` with a check for all SSH host keys.
Closes #793
=> fix: enhance check to regenerate SSH keys

CHANGELOG.md, builds/linux-storage.pkrvars.hcl.example, builds/linux/ubuntu/20-04-lts/data/storage.pkrtpl.hcl, builds/linux/ubuntu/22-04-lts/data/storage.pkrtpl.hcl, builds/linux/ubuntu/23-10/data/storage.pkrtpl.hcl, docs/getting-started/configuration.md, mkdocs.yml
For Ubuntu using autoinstall, add the possibility of using the value "-1" for the size of the last LVM partition, so that it uses the remaining space in the Volume Group.
Resolves #803
=> feat: growing ubuntu lvm partition

CHANGELOG.md, builds/linux/debian/12/linux-debian.pkrvars.hcl.example, builds/windows/desktop/10/windows.pkrvars.hcl.example, builds/windows/desktop/11/windows.pkrvars.hcl.example, builds/windows/server/2022/windows-server.pkrvars.hcl.example
chore: Update Windows 10/11, Windows Server 2022, and Debian 12 ISOs to latest
Updates `.pkrvars.hcl.example` files to latest ISOs for:
- Windows 10
- Windows 11
- Windows Server 2022
- Debian 12
=> chore: Update Windows 10/11, Windows Server 2022, and Debian 12 ISOs

builds/linux/debian/11/linux-debian.pkrvars.hcl.example, builds/linux/debian/11/variables.pkr.hcl, builds/linux/debian/12/linux-debian.pkrvars.hcl.example, builds/linux/debian/12/variables.pkr.hcl
Sets `vm_boot_order` = "-" to clear the boot order and remove the boot delay on Debian.
Closes #814
=> fix: debian boot delay

builds/windows/desktop/10/variables.pkr.hcl, builds/windows/desktop/11/variables.pkr.hcl, builds/windows/server/2019/variables.pkr.hcl, builds/windows/server/2022/variables.pkr.hcl, builds/windows/server/2025/variables.pkr.hcl
Re-add `ansible_username` and `ansible_key` variables for Windows builds to remove validation warnings/errors.
Might have snuck in via PR 801
=> fix: re-add `ansible_username` and `ansible_key` variables for windows builds

build.sh, build.yaml
Add `ansible.pkrvars.hcl` and `proxy.pkrvars.hcl` to Windows builds in `build.yml` / `build.sh`
n/a
=> fix: add `ansible.pkrvars.hcl` and `proxy.pkrvars.hcl` to windows builds

ansible/roles/base/tasks/windows.yml
New Ansible scripts for Windows fail when trying to install/use Chocolately on Windows Server 2019 (Desktop Experiece).
Since v2.0 Chocolately requires .NET Framework 4.8 which is not present on Windows Server 2019.
This change installs .NET 4.8 Framework before installing/using Chocolately.
- Resolves #841 
Issue Number: #841
=> Fix Windows Server 2019 Desktop Experience builds
